/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmbedTextResponse
 */
export interface EmbedTextResponse {
    /**
     * Vector embedding
     * @type {Array<number>}
     * @memberof EmbedTextResponse
     */
    embedding: Array<number>;
    /**
     * Embedding dimension
     * @type {number}
     * @memberof EmbedTextResponse
     */
    dimension: number;
    /**
     * Model used for embedding
     * @type {string}
     * @memberof EmbedTextResponse
     */
    model: string;
    /**
     * Unique identifier for this embedding
     * @type {string}
     * @memberof EmbedTextResponse
     */
    embeddingId: string;
}

/**
 * Check if a given object implements the EmbedTextResponse interface.
 */
export function instanceOfEmbedTextResponse(value: object): value is EmbedTextResponse {
    if (!('embedding' in value) || value['embedding'] === undefined) return false;
    if (!('dimension' in value) || value['dimension'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('embeddingId' in value) || value['embeddingId'] === undefined) return false;
    return true;
}

export function EmbedTextResponseFromJSON(json: any): EmbedTextResponse {
    return EmbedTextResponseFromJSONTyped(json, false);
}

export function EmbedTextResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbedTextResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'embedding': json['embedding'],
        'dimension': json['dimension'],
        'model': json['model'],
        'embeddingId': json['embedding_id'],
    };
}

export function EmbedTextResponseToJSON(json: any): EmbedTextResponse {
    return EmbedTextResponseToJSONTyped(json, false);
}

export function EmbedTextResponseToJSONTyped(value?: EmbedTextResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'embedding': value['embedding'],
        'dimension': value['dimension'],
        'model': value['model'],
        'embedding_id': value['embeddingId'],
    };
}

