/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmbedTextRequest
 */
export interface EmbedTextRequest {
    /**
     * Text to embed
     * @type {string}
     * @memberof EmbedTextRequest
     */
    text: string;
    /**
     * Optional embedding model identifier
     * @type {string}
     * @memberof EmbedTextRequest
     */
    model?: string;
}

/**
 * Check if a given object implements the EmbedTextRequest interface.
 */
export function instanceOfEmbedTextRequest(value: object): value is EmbedTextRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function EmbedTextRequestFromJSON(json: any): EmbedTextRequest {
    return EmbedTextRequestFromJSONTyped(json, false);
}

export function EmbedTextRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbedTextRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'model': json['model'] == null ? undefined : json['model'],
    };
}

export function EmbedTextRequestToJSON(json: any): EmbedTextRequest {
    return EmbedTextRequestToJSONTyped(json, false);
}

export function EmbedTextRequestToJSONTyped(value?: EmbedTextRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'model': value['model'],
    };
}

