/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmbedText200Response
 */
export interface EmbedText200Response {
    /**
     * Vector embedding
     * @type {Array<number>}
     * @memberof EmbedText200Response
     */
    embedding?: Array<number>;
    /**
     * Embedding dimension
     * @type {number}
     * @memberof EmbedText200Response
     */
    dimension?: number;
    /**
     * Model used for embedding
     * @type {string}
     * @memberof EmbedText200Response
     */
    model?: string;
}

/**
 * Check if a given object implements the EmbedText200Response interface.
 */
export function instanceOfEmbedText200Response(value: object): value is EmbedText200Response {
    return true;
}

export function EmbedText200ResponseFromJSON(json: any): EmbedText200Response {
    return EmbedText200ResponseFromJSONTyped(json, false);
}

export function EmbedText200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbedText200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'embedding': json['embedding'] == null ? undefined : json['embedding'],
        'dimension': json['dimension'] == null ? undefined : json['dimension'],
        'model': json['model'] == null ? undefined : json['model'],
    };
}

export function EmbedText200ResponseToJSON(json: any): EmbedText200Response {
    return EmbedText200ResponseToJSONTyped(json, false);
}

export function EmbedText200ResponseToJSONTyped(value?: EmbedText200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'embedding': value['embedding'],
        'dimension': value['dimension'],
        'model': value['model'],
    };
}

