/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Entity
 */
export interface Entity {
    /**
     * 
     * @type {string}
     * @memberof Entity
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof Entity
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof Entity
     */
    start: number;
    /**
     * 
     * @type {number}
     * @memberof Entity
     */
    end: number;
}

/**
 * Check if a given object implements the Entity interface.
 */
export function instanceOfEntity(value: object): value is Entity {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function EntityFromJSON(json: any): Entity {
    return EntityFromJSONTyped(json, false);
}

export function EntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Entity {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'label': json['label'],
        'start': json['start'],
        'end': json['end'],
    };
}

export function EntityToJSON(json: any): Entity {
    return EntityToJSONTyped(json, false);
}

export function EntityToJSONTyped(value?: Entity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'label': value['label'],
        'start': value['start'],
        'end': value['end'],
    };
}

