/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     * Overall health status
     * @type {string}
     * @memberof HealthResponse
     */
    status: string;
    /**
     * API version
     * @type {string}
     * @memberof HealthResponse
     */
    version: string;
    /**
     * Status of individual services
     * @type {{ [key: string]: string; }}
     * @memberof HealthResponse
     */
    services: { [key: string]: string; };
    /**
     * Milvus connectivity status
     * @type {{ [key: string]: any; }}
     * @memberof HealthResponse
     */
    milvus: { [key: string]: any; };
    /**
     * Internal queue status
     * @type {{ [key: string]: any; }}
     * @memberof HealthResponse
     */
    queue: { [key: string]: any; };
    /**
     * LLM provider configuration status
     * @type {{ [key: string]: any; }}
     * @memberof HealthResponse
     */
    llm: { [key: string]: any; };
}

/**
 * Check if a given object implements the HealthResponse interface.
 */
export function instanceOfHealthResponse(value: object): value is HealthResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    if (!('milvus' in value) || value['milvus'] === undefined) return false;
    if (!('queue' in value) || value['queue'] === undefined) return false;
    if (!('llm' in value) || value['llm'] === undefined) return false;
    return true;
}

export function HealthResponseFromJSON(json: any): HealthResponse {
    return HealthResponseFromJSONTyped(json, false);
}

export function HealthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'version': json['version'],
        'services': json['services'],
        'milvus': json['milvus'],
        'queue': json['queue'],
        'llm': json['llm'],
    };
}

export function HealthResponseToJSON(json: any): HealthResponse {
    return HealthResponseToJSONTyped(json, false);
}

export function HealthResponseToJSONTyped(value?: HealthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'version': value['version'],
        'services': value['services'],
        'milvus': value['milvus'],
        'queue': value['queue'],
        'llm': value['llm'],
    };
}

