/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LLMMessage } from './LLMMessage';
import {
    LLMMessageFromJSON,
    LLMMessageFromJSONTyped,
    LLMMessageToJSON,
    LLMMessageToJSONTyped,
} from './LLMMessage';

/**
 * 
 * @export
 * @interface LLMChoice
 */
export interface LLMChoice {
    /**
     * Choice index.
     * @type {number}
     * @memberof LLMChoice
     */
    index: number;
    /**
     * Assistant message payload.
     * @type {LLMMessage}
     * @memberof LLMChoice
     */
    message: LLMMessage;
    /**
     * Reason generation completed.
     * @type {string}
     * @memberof LLMChoice
     */
    finishReason?: string;
}

/**
 * Check if a given object implements the LLMChoice interface.
 */
export function instanceOfLLMChoice(value: object): value is LLMChoice {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LLMChoiceFromJSON(json: any): LLMChoice {
    return LLMChoiceFromJSONTyped(json, false);
}

export function LLMChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LLMChoice {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'message': LLMMessageFromJSON(json['message']),
        'finishReason': json['finish_reason'] == null ? undefined : json['finish_reason'],
    };
}

export function LLMChoiceToJSON(json: any): LLMChoice {
    return LLMChoiceToJSONTyped(json, false);
}

export function LLMChoiceToJSONTyped(value?: LLMChoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'message': LLMMessageToJSON(value['message']),
        'finish_reason': value['finishReason'],
    };
}

