/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LLMMessage
 */
export interface LLMMessage {
    /**
     * Role of the message.
     * @type {string}
     * @memberof LLMMessage
     */
    role: LLMMessageRoleEnum;
    /**
     * Text content of the message.
     * @type {string}
     * @memberof LLMMessage
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof LLMMessage
     */
    name?: string | null;
}


/**
 * @export
 */
export const LLMMessageRoleEnum = {
    System: 'system',
    User: 'user',
    Assistant: 'assistant',
    Tool: 'tool'
} as const;
export type LLMMessageRoleEnum = typeof LLMMessageRoleEnum[keyof typeof LLMMessageRoleEnum];


/**
 * Check if a given object implements the LLMMessage interface.
 */
export function instanceOfLLMMessage(value: object): value is LLMMessage {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function LLMMessageFromJSON(json: any): LLMMessage {
    return LLMMessageFromJSONTyped(json, false);
}

export function LLMMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LLMMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': json['content'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function LLMMessageToJSON(json: any): LLMMessage {
    return LLMMessageToJSONTyped(json, false);
}

export function LLMMessageToJSONTyped(value?: LLMMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': value['content'],
        'name': value['name'],
    };
}

