/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Chat completion message payload.
 * @export
 * @interface LLMMessage
 */
export interface LLMMessage {
    /**
     * Role associated with the message.
     * @type {string}
     * @memberof LLMMessage
     */
    role: LLMMessageRoleEnum;
    /**
     * Text content of the message.
     * @type {string}
     * @memberof LLMMessage
     */
    content: string;
    /**
     * Optional identifier for tool/function calls.
     * @type {string}
     * @memberof LLMMessage
     */
    name?: string;
}


/**
 * @export
 */
export const LLMMessageRoleEnum = {
    System: 'system',
    User: 'user',
    Assistant: 'assistant',
    Tool: 'tool'
} as const;
export type LLMMessageRoleEnum = typeof LLMMessageRoleEnum[keyof typeof LLMMessageRoleEnum];


/**
 * Check if a given object implements the LLMMessage interface.
 */
export function instanceOfLLMMessage(value: object): value is LLMMessage {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function LLMMessageFromJSON(json: any): LLMMessage {
    return LLMMessageFromJSONTyped(json, false);
}

export function LLMMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LLMMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': json['content'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function LLMMessageToJSON(json: any): LLMMessage {
    return LLMMessageToJSONTyped(json, false);
}

export function LLMMessageToJSONTyped(value?: LLMMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': value['content'],
        'name': value['name'],
    };
}

