/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LLMChoice } from './LLMChoice';
import {
    LLMChoiceFromJSON,
    LLMChoiceFromJSONTyped,
    LLMChoiceToJSON,
    LLMChoiceToJSONTyped,
} from './LLMChoice';
import type { LLMUsage } from './LLMUsage';
import {
    LLMUsageFromJSON,
    LLMUsageFromJSONTyped,
    LLMUsageToJSON,
    LLMUsageToJSONTyped,
} from './LLMUsage';

/**
 * 
 * @export
 * @interface LLMResponse
 */
export interface LLMResponse {
    /**
     * Provider response identifier.
     * @type {string}
     * @memberof LLMResponse
     */
    id: string;
    /**
     * Provider used for the completion.
     * @type {string}
     * @memberof LLMResponse
     */
    provider: string;
    /**
     * Provider model identifier.
     * @type {string}
     * @memberof LLMResponse
     */
    model: string;
    /**
     * Epoch timestamp when created.
     * @type {number}
     * @memberof LLMResponse
     */
    created: number;
    /**
     * Choices returned by provider.
     * @type {Array<LLMChoice>}
     * @memberof LLMResponse
     */
    choices: Array<LLMChoice>;
    /**
     * 
     * @type {LLMUsage}
     * @memberof LLMResponse
     */
    usage?: LLMUsage | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LLMResponse
     */
    raw?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the LLMResponse interface.
 */
export function instanceOfLLMResponse(value: object): value is LLMResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('choices' in value) || value['choices'] === undefined) return false;
    return true;
}

export function LLMResponseFromJSON(json: any): LLMResponse {
    return LLMResponseFromJSONTyped(json, false);
}

export function LLMResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LLMResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'provider': json['provider'],
        'model': json['model'],
        'created': json['created'],
        'choices': ((json['choices'] as Array<any>).map(LLMChoiceFromJSON)),
        'usage': json['usage'] == null ? undefined : LLMUsageFromJSON(json['usage']),
        'raw': json['raw'] == null ? undefined : json['raw'],
    };
}

export function LLMResponseToJSON(json: any): LLMResponse {
    return LLMResponseToJSONTyped(json, false);
}

export function LLMResponseToJSONTyped(value?: LLMResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'provider': value['provider'],
        'model': value['model'],
        'created': value['created'],
        'choices': ((value['choices'] as Array<any>).map(LLMChoiceToJSON)),
        'usage': LLMUsageToJSON(value['usage']),
        'raw': value['raw'],
    };
}

