/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LLMMessage } from './LLMMessage';
import {
    LLMMessageFromJSON,
    LLMMessageFromJSONTyped,
    LLMMessageToJSON,
    LLMMessageToJSONTyped,
} from './LLMMessage';

/**
 * 
 * @export
 * @interface LLMRequest
 */
export interface LLMRequest {
    /**
     * 
     * @type {string}
     * @memberof LLMRequest
     */
    prompt?: string | null;
    /**
     * 
     * @type {Array<LLMMessage>}
     * @memberof LLMRequest
     */
    messages?: Array<LLMMessage> | null;
    /**
     * 
     * @type {string}
     * @memberof LLMRequest
     */
    provider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LLMRequest
     */
    model?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LLMRequest
     */
    temperature?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LLMRequest
     */
    maxTokens?: number | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LLMRequest
     */
    metadata?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the LLMRequest interface.
 */
export function instanceOfLLMRequest(value: object): value is LLMRequest {
    return true;
}

export function LLMRequestFromJSON(json: any): LLMRequest {
    return LLMRequestFromJSONTyped(json, false);
}

export function LLMRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LLMRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(LLMMessageFromJSON)),
        'provider': json['provider'] == null ? undefined : json['provider'],
        'model': json['model'] == null ? undefined : json['model'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'maxTokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function LLMRequestToJSON(json: any): LLMRequest {
    return LLMRequestToJSONTyped(json, false);
}

export function LLMRequestToJSONTyped(value?: LLMRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(LLMMessageToJSON)),
        'provider': value['provider'],
        'model': value['model'],
        'temperature': value['temperature'],
        'max_tokens': value['maxTokens'],
        'metadata': value['metadata'],
    };
}

