/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Token usage returned by the upstream provider.
 * @export
 * @interface LLMUsage
 */
export interface LLMUsage {
    /**
     * Prompt token count.
     * @type {number}
     * @memberof LLMUsage
     */
    promptTokens: number;
    /**
     * Completion token count.
     * @type {number}
     * @memberof LLMUsage
     */
    completionTokens: number;
    /**
     * Total token count.
     * @type {number}
     * @memberof LLMUsage
     */
    totalTokens: number;
}

/**
 * Check if a given object implements the LLMUsage interface.
 */
export function instanceOfLLMUsage(value: object): value is LLMUsage {
    if (!('promptTokens' in value) || value['promptTokens'] === undefined) return false;
    if (!('completionTokens' in value) || value['completionTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function LLMUsageFromJSON(json: any): LLMUsage {
    return LLMUsageFromJSONTyped(json, false);
}

export function LLMUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LLMUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'promptTokens': json['prompt_tokens'],
        'completionTokens': json['completion_tokens'],
        'totalTokens': json['total_tokens'],
    };
}

export function LLMUsageToJSON(json: any): LLMUsage {
    return LLMUsageToJSONTyped(json, false);
}

export function LLMUsageToJSONTyped(value?: LLMUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt_tokens': value['promptTokens'],
        'completion_tokens': value['completionTokens'],
        'total_tokens': value['totalTokens'],
    };
}

