/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POSTag
 */
export interface POSTag {
    /**
     * 
     * @type {string}
     * @memberof POSTag
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof POSTag
     */
    tag: string;
}

/**
 * Check if a given object implements the POSTag interface.
 */
export function instanceOfPOSTag(value: object): value is POSTag {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    return true;
}

export function POSTagFromJSON(json: any): POSTag {
    return POSTagFromJSONTyped(json, false);
}

export function POSTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSTag {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'tag': json['tag'],
    };
}

export function POSTagToJSON(json: any): POSTag {
    return POSTagToJSONTyped(json, false);
}

export function POSTagToJSONTyped(value?: POSTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'tag': value['tag'],
    };
}

