/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityFromJSONTyped,
    EntityToJSON,
    EntityToJSONTyped,
} from './Entity';
import type { POSTag } from './POSTag';
import {
    POSTagFromJSON,
    POSTagFromJSONTyped,
    POSTagToJSON,
    POSTagToJSONTyped,
} from './POSTag';

/**
 * 
 * @export
 * @interface SimpleNLPResponse
 */
export interface SimpleNLPResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof SimpleNLPResponse
     */
    tokens?: Array<string> | null;
    /**
     * 
     * @type {Array<POSTag>}
     * @memberof SimpleNLPResponse
     */
    posTags?: Array<POSTag> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SimpleNLPResponse
     */
    lemmas?: Array<string> | null;
    /**
     * 
     * @type {Array<Entity>}
     * @memberof SimpleNLPResponse
     */
    entities?: Array<Entity> | null;
}

/**
 * Check if a given object implements the SimpleNLPResponse interface.
 */
export function instanceOfSimpleNLPResponse(value: object): value is SimpleNLPResponse {
    return true;
}

export function SimpleNLPResponseFromJSON(json: any): SimpleNLPResponse {
    return SimpleNLPResponseFromJSONTyped(json, false);
}

export function SimpleNLPResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleNLPResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tokens': json['tokens'] == null ? undefined : json['tokens'],
        'posTags': json['pos_tags'] == null ? undefined : ((json['pos_tags'] as Array<any>).map(POSTagFromJSON)),
        'lemmas': json['lemmas'] == null ? undefined : json['lemmas'],
        'entities': json['entities'] == null ? undefined : ((json['entities'] as Array<any>).map(EntityFromJSON)),
    };
}

export function SimpleNLPResponseToJSON(json: any): SimpleNLPResponse {
    return SimpleNLPResponseToJSONTyped(json, false);
}

export function SimpleNLPResponseToJSONTyped(value?: SimpleNLPResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokens': value['tokens'],
        'pos_tags': value['posTags'] == null ? undefined : ((value['posTags'] as Array<any>).map(POSTagToJSON)),
        'lemmas': value['lemmas'],
        'entities': value['entities'] == null ? undefined : ((value['entities'] as Array<any>).map(EntityToJSON)),
    };
}

