/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleNlpRequest
 */
export interface SimpleNlpRequest {
    /**
     * Text to process
     * @type {string}
     * @memberof SimpleNlpRequest
     */
    text: string;
    /**
     * List of NLP operations to perform
     * @type {Array<string>}
     * @memberof SimpleNlpRequest
     */
    operations?: Array<SimpleNlpRequestOperationsEnum>;
}


/**
 * @export
 */
export const SimpleNlpRequestOperationsEnum = {
    Tokenize: 'tokenize',
    PosTag: 'pos_tag',
    Lemmatize: 'lemmatize',
    Ner: 'ner'
} as const;
export type SimpleNlpRequestOperationsEnum = typeof SimpleNlpRequestOperationsEnum[keyof typeof SimpleNlpRequestOperationsEnum];


/**
 * Check if a given object implements the SimpleNlpRequest interface.
 */
export function instanceOfSimpleNlpRequest(value: object): value is SimpleNlpRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SimpleNlpRequestFromJSON(json: any): SimpleNlpRequest {
    return SimpleNlpRequestFromJSONTyped(json, false);
}

export function SimpleNlpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleNlpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'operations': json['operations'] == null ? undefined : json['operations'],
    };
}

export function SimpleNlpRequestToJSON(json: any): SimpleNlpRequest {
    return SimpleNlpRequestToJSONTyped(json, false);
}

export function SimpleNlpRequestToJSONTyped(value?: SimpleNlpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'operations': value['operations'],
    };
}

