/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleNLPRequest
 */
export interface SimpleNLPRequest {
    /**
     * Text to process
     * @type {string}
     * @memberof SimpleNLPRequest
     */
    text: string;
    /**
     * List of NLP operations to perform
     * @type {Array<string>}
     * @memberof SimpleNLPRequest
     */
    operations?: Array<string>;
}

/**
 * Check if a given object implements the SimpleNLPRequest interface.
 */
export function instanceOfSimpleNLPRequest(value: object): value is SimpleNLPRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SimpleNLPRequestFromJSON(json: any): SimpleNLPRequest {
    return SimpleNLPRequestFromJSONTyped(json, false);
}

export function SimpleNLPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleNLPRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'operations': json['operations'] == null ? undefined : json['operations'],
    };
}

export function SimpleNLPRequestToJSON(json: any): SimpleNLPRequest {
    return SimpleNLPRequestToJSONTyped(json, false);
}

export function SimpleNLPRequestToJSONTyped(value?: SimpleNLPRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'operations': value['operations'],
    };
}

