/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimpleNlp200ResponsePosTagsInner } from './SimpleNlp200ResponsePosTagsInner';
import {
    SimpleNlp200ResponsePosTagsInnerFromJSON,
    SimpleNlp200ResponsePosTagsInnerFromJSONTyped,
    SimpleNlp200ResponsePosTagsInnerToJSON,
    SimpleNlp200ResponsePosTagsInnerToJSONTyped,
} from './SimpleNlp200ResponsePosTagsInner';
import type { SimpleNlp200ResponseEntitiesInner } from './SimpleNlp200ResponseEntitiesInner';
import {
    SimpleNlp200ResponseEntitiesInnerFromJSON,
    SimpleNlp200ResponseEntitiesInnerFromJSONTyped,
    SimpleNlp200ResponseEntitiesInnerToJSON,
    SimpleNlp200ResponseEntitiesInnerToJSONTyped,
} from './SimpleNlp200ResponseEntitiesInner';

/**
 * 
 * @export
 * @interface SimpleNlp200Response
 */
export interface SimpleNlp200Response {
    /**
     * Tokenized text (if requested)
     * @type {Array<string>}
     * @memberof SimpleNlp200Response
     */
    tokens?: Array<string>;
    /**
     * POS tags (if requested)
     * @type {Array<SimpleNlp200ResponsePosTagsInner>}
     * @memberof SimpleNlp200Response
     */
    posTags?: Array<SimpleNlp200ResponsePosTagsInner>;
    /**
     * Lemmatized tokens (if requested)
     * @type {Array<string>}
     * @memberof SimpleNlp200Response
     */
    lemmas?: Array<string>;
    /**
     * Named entities (if requested)
     * @type {Array<SimpleNlp200ResponseEntitiesInner>}
     * @memberof SimpleNlp200Response
     */
    entities?: Array<SimpleNlp200ResponseEntitiesInner>;
}

/**
 * Check if a given object implements the SimpleNlp200Response interface.
 */
export function instanceOfSimpleNlp200Response(value: object): value is SimpleNlp200Response {
    return true;
}

export function SimpleNlp200ResponseFromJSON(json: any): SimpleNlp200Response {
    return SimpleNlp200ResponseFromJSONTyped(json, false);
}

export function SimpleNlp200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleNlp200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'tokens': json['tokens'] == null ? undefined : json['tokens'],
        'posTags': json['pos_tags'] == null ? undefined : ((json['pos_tags'] as Array<any>).map(SimpleNlp200ResponsePosTagsInnerFromJSON)),
        'lemmas': json['lemmas'] == null ? undefined : json['lemmas'],
        'entities': json['entities'] == null ? undefined : ((json['entities'] as Array<any>).map(SimpleNlp200ResponseEntitiesInnerFromJSON)),
    };
}

export function SimpleNlp200ResponseToJSON(json: any): SimpleNlp200Response {
    return SimpleNlp200ResponseToJSONTyped(json, false);
}

export function SimpleNlp200ResponseToJSONTyped(value?: SimpleNlp200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokens': value['tokens'],
        'pos_tags': value['posTags'] == null ? undefined : ((value['posTags'] as Array<any>).map(SimpleNlp200ResponsePosTagsInnerToJSON)),
        'lemmas': value['lemmas'],
        'entities': value['entities'] == null ? undefined : ((value['entities'] as Array<any>).map(SimpleNlp200ResponseEntitiesInnerToJSON)),
    };
}

