/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpeechToText200Response
 */
export interface SpeechToText200Response {
    /**
     * Transcribed text
     * @type {string}
     * @memberof SpeechToText200Response
     */
    text?: string;
    /**
     * Confidence score (0.0 to 1.0)
     * @type {number}
     * @memberof SpeechToText200Response
     */
    confidence?: number;
}

/**
 * Check if a given object implements the SpeechToText200Response interface.
 */
export function instanceOfSpeechToText200Response(value: object): value is SpeechToText200Response {
    return true;
}

export function SpeechToText200ResponseFromJSON(json: any): SpeechToText200Response {
    return SpeechToText200ResponseFromJSONTyped(json, false);
}

export function SpeechToText200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpeechToText200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
    };
}

export function SpeechToText200ResponseToJSON(json: any): SpeechToText200Response {
    return SpeechToText200ResponseToJSONTyped(json, false);
}

export function SpeechToText200ResponseToJSONTyped(value?: SpeechToText200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'confidence': value['confidence'],
    };
}

