/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface STTResponse
 */
export interface STTResponse {
    /**
     * Transcribed text
     * @type {string}
     * @memberof STTResponse
     */
    text: string;
    /**
     * Confidence score (0.0 to 1.0)
     * @type {number}
     * @memberof STTResponse
     */
    confidence: number;
}

/**
 * Check if a given object implements the STTResponse interface.
 */
export function instanceOfSTTResponse(value: object): value is STTResponse {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    return true;
}

export function STTResponseFromJSON(json: any): STTResponse {
    return STTResponseFromJSONTyped(json, false);
}

export function STTResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): STTResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'confidence': json['confidence'],
    };
}

export function STTResponseToJSON(json: any): STTResponse {
    return STTResponseToJSONTyped(json, false);
}

export function STTResponseToJSONTyped(value?: STTResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'confidence': value['confidence'],
    };
}

