
"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, StrictStr
from typing_extensions import Self


class CWMStateLinks(BaseModel):
    """
    References to related HCG entities
    """ # noqa: E501
    process_ids: list[StrictStr] | None = None
    plan_id: StrictStr | None = None
    entity_ids: list[StrictStr] | None = None
    media_sample_id: StrictStr | None = None
    persona_entry_id: StrictStr | None = None
    talos_run_id: StrictStr | None = None
    __properties: ClassVar[list[str]] = ["process_ids", "plan_id", "entity_ids", "media_sample_id", "persona_entry_id", "talos_run_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CWMStateLinks from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of CWMStateLinks from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "process_ids": obj.get("process_ids"),
            "plan_id": obj.get("plan_id"),
            "entity_ids": obj.get("entity_ids"),
            "media_sample_id": obj.get("media_sample_id"),
            "persona_entry_id": obj.get("persona_entry_id"),
            "talos_run_id": obj.get("talos_run_id")
        })
        return _obj


