# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from sophia_client.models.cwm_state import CWMState
from sophia_client.models.generate_plan200_response_causal_links_inner import GeneratePlan200ResponseCausalLinksInner
from sophia_client.models.generate_plan200_response_processes_inner import GeneratePlan200ResponseProcessesInner
from typing import Optional, Set
from typing_extensions import Self

class GeneratePlan200Response(BaseModel):
    """
    GeneratePlan200Response
    """ # noqa: E501
    plan_id: Optional[StrictStr] = Field(default=None, description="Unique identifier for the generated plan")
    processes: Optional[List[GeneratePlan200ResponseProcessesInner]] = None
    causal_links: Optional[List[GeneratePlan200ResponseCausalLinksInner]] = None
    cwm_states: Optional[List[CWMState]] = Field(default=None, description="Newly created CWMState records from planning")
    confidence: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Overall plan confidence (0.0 to 1.0)")
    __properties: ClassVar[List[str]] = ["plan_id", "processes", "causal_links", "cwm_states", "confidence"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeneratePlan200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in processes (list)
        _items = []
        if self.processes:
            for _item_processes in self.processes:
                if _item_processes:
                    _items.append(_item_processes.to_dict())
            _dict['processes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in causal_links (list)
        _items = []
        if self.causal_links:
            for _item_causal_links in self.causal_links:
                if _item_causal_links:
                    _items.append(_item_causal_links.to_dict())
            _dict['causal_links'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cwm_states (list)
        _items = []
        if self.cwm_states:
            for _item_cwm_states in self.cwm_states:
                if _item_cwm_states:
                    _items.append(_item_cwm_states.to_dict())
            _dict['cwm_states'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeneratePlan200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "plan_id": obj.get("plan_id"),
            "processes": [GeneratePlan200ResponseProcessesInner.from_dict(_item) for _item in obj["processes"]] if obj.get("processes") is not None else None,
            "causal_links": [GeneratePlan200ResponseCausalLinksInner.from_dict(_item) for _item in obj["causal_links"]] if obj.get("causal_links") is not None else None,
            "cwm_states": [CWMState.from_dict(_item) for _item in obj["cwm_states"]] if obj.get("cwm_states") is not None else None,
            "confidence": obj.get("confidence")
        })
        return _obj


