# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sophia_client.models.get_health200_response_milvus import GetHealth200ResponseMilvus
from sophia_client.models.get_health200_response_neo4j import GetHealth200ResponseNeo4j
from typing import Optional, Set
from typing_extensions import Self

class GetHealth200Response(BaseModel):
    """
    GetHealth200Response
    """ # noqa: E501
    status: Optional[StrictStr] = None
    neo4j: Optional[GetHealth200ResponseNeo4j] = None
    milvus: Optional[GetHealth200ResponseMilvus] = None
    timestamp: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["status", "neo4j", "milvus", "timestamp"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['healthy', 'degraded', 'unhealthy']):
            raise ValueError("must be one of enum values ('healthy', 'degraded', 'unhealthy')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetHealth200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of neo4j
        if self.neo4j:
            _dict['neo4j'] = self.neo4j.to_dict()
        # override the default output from pydantic by calling `to_dict()` of milvus
        if self.milvus:
            _dict['milvus'] = self.milvus.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetHealth200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "neo4j": GetHealth200ResponseNeo4j.from_dict(obj["neo4j"]) if obj.get("neo4j") is not None else None,
            "milvus": GetHealth200ResponseMilvus.from_dict(obj["milvus"]) if obj.get("milvus") is not None else None,
            "timestamp": obj.get("timestamp")
        })
        return _obj


