# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from sophia_client.models.cwm_state import CWMState
from sophia_client.models.run_simulation200_response_metadata import RunSimulation200ResponseMetadata
from sophia_client.models.run_simulation200_response_predicted_outcomes_inner import RunSimulation200ResponsePredictedOutcomesInner
from typing import Optional, Set
from typing_extensions import Self

class RunSimulation200Response(BaseModel):
    """
    RunSimulation200Response
    """ # noqa: E501
    simulation_id: Optional[StrictStr] = Field(default=None, description="Unique identifier for this simulation run")
    imagined_states: Optional[List[CWMState]] = None
    predicted_outcomes: Optional[List[RunSimulation200ResponsePredictedOutcomesInner]] = None
    metadata: Optional[RunSimulation200ResponseMetadata] = None
    __properties: ClassVar[List[str]] = ["simulation_id", "imagined_states", "predicted_outcomes", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RunSimulation200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in imagined_states (list)
        _items = []
        if self.imagined_states:
            for _item_imagined_states in self.imagined_states:
                if _item_imagined_states:
                    _items.append(_item_imagined_states.to_dict())
            _dict['imagined_states'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in predicted_outcomes (list)
        _items = []
        if self.predicted_outcomes:
            for _item_predicted_outcomes in self.predicted_outcomes:
                if _item_predicted_outcomes:
                    _items.append(_item_predicted_outcomes.to_dict())
            _dict['predicted_outcomes'] = _items
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RunSimulation200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "simulation_id": obj.get("simulation_id"),
            "imagined_states": [CWMState.from_dict(_item) for _item in obj["imagined_states"]] if obj.get("imagined_states") is not None else None,
            "predicted_outcomes": [RunSimulation200ResponsePredictedOutcomesInner.from_dict(_item) for _item in obj["predicted_outcomes"]] if obj.get("predicted_outcomes") is not None else None,
            "metadata": RunSimulation200ResponseMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None
        })
        return _obj


