
"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self


class RunSimulation200ResponsePredictedOutcomesInner(BaseModel):
    """
    RunSimulation200ResponsePredictedOutcomesInner
    """ # noqa: E501
    entity_id: StrictStr | None = None
    predicted_state: StrictStr | None = None
    confidence: StrictFloat | StrictInt | None = None
    timestep: StrictInt | None = None
    __properties: ClassVar[list[str]] = ["entity_id", "predicted_state", "confidence", "timestep"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of RunSimulation200ResponsePredictedOutcomesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of RunSimulation200ResponsePredictedOutcomesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "entity_id": obj.get("entity_id"),
            "predicted_state": obj.get("predicted_state"),
            "confidence": obj.get("confidence"),
            "timestep": obj.get("timestep")
        })
        return _obj


