
"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophia_client.models.run_simulation200_response import RunSimulation200Response


class TestRunSimulation200Response(unittest.TestCase):
    """RunSimulation200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunSimulation200Response:
        """Test RunSimulation200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunSimulation200Response`
        """
        model = RunSimulation200Response()
        if include_optional:
            return RunSimulation200Response(
                simulation_id = '',
                imagined_states = [
                    sophia_client.models.cwm_state.CWMState(
                        state_id = '',
                        model_type = 'CWM_A',
                        source = '',
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        confidence = 0.0,
                        status = 'observed',
                        links = sophia_client.models.cwm_state_links.CWMState_links(
                            process_ids = [
                                ''
                                ],
                            plan_id = '',
                            entity_ids = [
                                ''
                                ],
                            media_sample_id = '',
                            persona_entry_id = '',
                            talos_run_id = '', ),
                        tags = [
                            ''
                            ],
                        data = { }, )
                    ],
                predicted_outcomes = [
                    sophia_client.models.run_simulation_200_response_predicted_outcomes_inner.runSimulation_200_response_predicted_outcomes_inner(
                        entity_id = '',
                        predicted_state = '',
                        confidence = 1.337,
                        timestep = 56, )
                    ],
                metadata = sophia_client.models.run_simulation_200_response_metadata.runSimulation_200_response_metadata(
                    model_version = '',
                    horizon = 56,
                    assumptions = [
                        ''
                        ], )
            )
        else:
            return RunSimulation200Response(
        )
        """

    def testRunSimulation200Response(self):
        """Test RunSimulation200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
