# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophia_client.models.generate_plan_request_goal_state_entities_inner import GeneratePlanRequestGoalStateEntitiesInner

class TestGeneratePlanRequestGoalStateEntitiesInner(unittest.TestCase):
    """GeneratePlanRequestGoalStateEntitiesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeneratePlanRequestGoalStateEntitiesInner:
        """Test GeneratePlanRequestGoalStateEntitiesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneratePlanRequestGoalStateEntitiesInner`
        """
        model = GeneratePlanRequestGoalStateEntitiesInner()
        if include_optional:
            return GeneratePlanRequestGoalStateEntitiesInner(
                entity_id = '',
                desired_state = ''
            )
        else:
            return GeneratePlanRequestGoalStateEntitiesInner(
        )
        """

    def testGeneratePlanRequestGoalStateEntitiesInner(self):
        """Test GeneratePlanRequestGoalStateEntitiesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
