# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophia_client.models.run_simulation200_response_metadata import RunSimulation200ResponseMetadata

class TestRunSimulation200ResponseMetadata(unittest.TestCase):
    """RunSimulation200ResponseMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunSimulation200ResponseMetadata:
        """Test RunSimulation200ResponseMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunSimulation200ResponseMetadata`
        """
        model = RunSimulation200ResponseMetadata()
        if include_optional:
            return RunSimulation200ResponseMetadata(
                model_version = '',
                horizon = 56,
                assumptions = [
                    ''
                    ]
            )
        else:
            return RunSimulation200ResponseMetadata(
        )
        """

    def testRunSimulation200ResponseMetadata(self):
        """Test RunSimulation200ResponseMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
