
"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophia_client.models.get_health200_response_neo4j import GetHealth200ResponseNeo4j


class TestGetHealth200ResponseNeo4j(unittest.TestCase):
    """GetHealth200ResponseNeo4j unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetHealth200ResponseNeo4j:
        """Test GetHealth200ResponseNeo4j
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetHealth200ResponseNeo4j`
        """
        model = GetHealth200ResponseNeo4j()
        if include_optional:
            return GetHealth200ResponseNeo4j(
                connected = True,
                latency_ms = 1.337
            )
        else:
            return GetHealth200ResponseNeo4j(
        )
        """

    def testGetHealth200ResponseNeo4j(self):
        """Test GetHealth200ResponseNeo4j"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
