# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophia_client.models.generate_plan200_response import GeneratePlan200Response

class TestGeneratePlan200Response(unittest.TestCase):
    """GeneratePlan200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeneratePlan200Response:
        """Test GeneratePlan200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneratePlan200Response`
        """
        model = GeneratePlan200Response()
        if include_optional:
            return GeneratePlan200Response(
                plan_id = '',
                processes = [
                    sophia_client.models.generate_plan_200_response_processes_inner.generatePlan_200_response_processes_inner(
                        process_id = '', 
                        name = '', 
                        capability_id = '', 
                        preconditions = [
                            ''
                            ], 
                        effects = [
                            ''
                            ], 
                        estimated_duration = 1.337, )
                    ],
                causal_links = [
                    sophia_client.models.generate_plan_200_response_causal_links_inner.generatePlan_200_response_causal_links_inner(
                        from_process = '', 
                        to_process = '', 
                        condition = '', )
                    ],
                cwm_states = [
                    sophia_client.models.cwm_state.CWMState(
                        state_id = '', 
                        model_type = 'CWM_A', 
                        source = '', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        confidence = 0.0, 
                        status = 'observed', 
                        links = sophia_client.models.cwm_state_links.CWMState_links(
                            process_ids = [
                                ''
                                ], 
                            plan_id = '', 
                            entity_ids = [
                                ''
                                ], 
                            media_sample_id = '', 
                            persona_entry_id = '', 
                            talos_run_id = '', ), 
                        tags = [
                            ''
                            ], 
                        data = { }, )
                    ],
                confidence = 1.337
            )
        else:
            return GeneratePlan200Response(
        )
        """

    def testGeneratePlan200Response(self):
        """Test GeneratePlan200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
