
"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophia_client.models.generate_plan200_response_processes_inner import (
    GeneratePlan200ResponseProcessesInner,
)


class TestGeneratePlan200ResponseProcessesInner(unittest.TestCase):
    """GeneratePlan200ResponseProcessesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeneratePlan200ResponseProcessesInner:
        """Test GeneratePlan200ResponseProcessesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneratePlan200ResponseProcessesInner`
        """
        model = GeneratePlan200ResponseProcessesInner()
        if include_optional:
            return GeneratePlan200ResponseProcessesInner(
                process_id = '',
                name = '',
                capability_id = '',
                preconditions = [
                    ''
                    ],
                effects = [
                    ''
                    ],
                estimated_duration = 1.337
            )
        else:
            return GeneratePlan200ResponseProcessesInner(
        )
        """

    def testGeneratePlan200ResponseProcessesInner(self):
        """Test GeneratePlan200ResponseProcessesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
