
"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophia_client.models.get_health200_response import GetHealth200Response


class TestGetHealth200Response(unittest.TestCase):
    """GetHealth200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetHealth200Response:
        """Test GetHealth200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetHealth200Response`
        """
        model = GetHealth200Response()
        if include_optional:
            return GetHealth200Response(
                status = 'healthy',
                neo4j = sophia_client.models.get_health_200_response_neo4j.getHealth_200_response_neo4j(
                    connected = True,
                    latency_ms = 1.337, ),
                milvus = sophia_client.models.get_health_200_response_milvus.getHealth_200_response_milvus(
                    connected = True,
                    collections = [
                        ''
                        ], ),
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetHealth200Response(
        )
        """

    def testGetHealth200Response(self):
        """Test GetHealth200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
