# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophia_client.models.run_simulation200_response_predicted_outcomes_inner import RunSimulation200ResponsePredictedOutcomesInner

class TestRunSimulation200ResponsePredictedOutcomesInner(unittest.TestCase):
    """RunSimulation200ResponsePredictedOutcomesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunSimulation200ResponsePredictedOutcomesInner:
        """Test RunSimulation200ResponsePredictedOutcomesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunSimulation200ResponsePredictedOutcomesInner`
        """
        model = RunSimulation200ResponsePredictedOutcomesInner()
        if include_optional:
            return RunSimulation200ResponsePredictedOutcomesInner(
                entity_id = '',
                predicted_state = '',
                confidence = 1.337,
                timestep = 56
            )
        else:
            return RunSimulation200ResponsePredictedOutcomesInner(
        )
        """

    def testRunSimulation200ResponsePredictedOutcomesInner(self):
        """Test RunSimulation200ResponsePredictedOutcomesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
