# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophia_client.models.run_simulation_request import RunSimulationRequest

class TestRunSimulationRequest(unittest.TestCase):
    """RunSimulationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunSimulationRequest:
        """Test RunSimulationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunSimulationRequest`
        """
        model = RunSimulationRequest()
        if include_optional:
            return RunSimulationRequest(
                capability_id = '',
                context = sophia_client.models.run_simulation_request_context.runSimulation_request_context(
                    entity_ids = [
                        ''
                        ], 
                    media_sample_id = '', 
                    talos_metadata = {
                        'key' : null
                        }, 
                    horizon_steps = 56, )
            )
        else:
            return RunSimulationRequest(
                capability_id = '',
                context = sophia_client.models.run_simulation_request_context.runSimulation_request_context(
                    entity_ids = [
                        ''
                        ], 
                    media_sample_id = '', 
                    talos_metadata = {
                        'key' : null
                        }, 
                    horizon_steps = 56, ),
        )
        """

    def testRunSimulationRequest(self):
        """Test RunSimulationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
