# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophia_client.models.cwm_state import CWMState

class TestCWMState(unittest.TestCase):
    """CWMState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CWMState:
        """Test CWMState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CWMState`
        """
        model = CWMState()
        if include_optional:
            return CWMState(
                state_id = '',
                model_type = 'CWM_A',
                source = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                confidence = 0.0,
                status = 'observed',
                links = sophia_client.models.cwm_state_links.CWMState_links(
                    process_ids = [
                        ''
                        ], 
                    plan_id = '', 
                    entity_ids = [
                        ''
                        ], 
                    media_sample_id = '', 
                    persona_entry_id = '', 
                    talos_run_id = '', ),
                tags = [
                    ''
                    ],
                data = { }
            )
        else:
            return CWMState(
                state_id = '',
                model_type = 'CWM_A',
                source = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                confidence = 0.0,
                status = 'observed',
        )
        """

    def testCWMState(self):
        """Test CWMState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
