#!/bin/bash
# GitHub CLI commands to create issues for Project LOGOS
# Organized by epochs (milestones)
# Make sure you have gh CLI installed and authenticated

set -e  # Exit on error


# Epoch 1: Infrastructure & Knowledge Foundation
#  → M1: HCG Store & Retrieve

gh issue create --repo c-daly/logos --title "[TASK] Set up CI/CD for validation tests" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] **c-daly/sophia** — Cognitive core repository" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:sophia,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Initialize Python project structure" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Set up dependency management (Poetry/pipenv)" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Create skeleton modules: Orchestrator, CWM-A, CWM-G, Planner, Executor" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Add unit test framework (pytest)" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Create docker-compose for local development" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] **c-daly/hermes** — Language utility repository" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "component:hermes,priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Initialize Python project structure" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Implement FastAPI application skeleton" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Implement `/stt` endpoint stub" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Implement `/tts` endpoint stub" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Implement `/simple_nlp` endpoint stub" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Implement `/embed_text` endpoint stub" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Add OpenAPI validation tests" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Create Dockerfile" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] **c-daly/talos** — Hardware abstraction repository" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,component:infrastructure,phase:1,component:talos" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Initialize Python project structure" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Define sensor/actuator interface abstractions" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Implement simulated sensors (camera, depth, IMU)" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Implement simulated actuators (motors, grippers)" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Add mock hardware for Phase 1 testing" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] **c-daly/apollo** — UI/client repository" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "component:apollo,phase:1,priority:high,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Initialize Node.js/React project" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Create basic dashboard layout" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Add HCG visualization component (graph view)" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Add command input interface" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Add real-time state monitoring display" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Create GitHub Project board for LOGOS (infrastructure ready in `.github/project_config.yml`)" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Set up milestone: \"Phase 1 — HCG and Abstract Pipeline\" (see `.github/PROJECT_BOARD_SETUP.md`)" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Create issues for all Phase 1 tasks (use `.github/scripts/generate_issues.py`)" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Initialize Neo4j with neosemantics plugin" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Load core ontology constraints into Neo4j" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Set up SHACL validation endpoint" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Configure Milvus collections for embeddings" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Create backup/restore scripts for development data" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[TASK] Document infrastructure setup in logos README" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[A1] Extend core ontology" --body "**Reference:** Section 4.1, Appendix A\n**Workstream:** Workstream A: HCG Foundation and Validation\n**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation\n
**Acceptance Criteria:**\n- [ ] Define all entity types for \"pick and place\" scenario\n- [ ] Define all relationship types (IS_A, HAS_STATE, CAUSES, PART_OF, etc.)\n- [ ] Add property schemas for entities (position, orientation, etc.)\n- [ ] Create Cypher scripts for test data population" --label "priority:high,workstream:A,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[A4] HCG query utilities" --body "**Workstream:** Workstream A: HCG Foundation and Validation\n**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation\n
**Acceptance Criteria:**\n- [ ] Write Cypher queries for common graph operations (find entity, traverse causality, etc.)\n- [ ] Create Python client library for HCG access\n- [ ] Add connection pooling and error handling\n- [ ] Write integration tests for HCG operations" --label "priority:high,workstream:A,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[M1] HCG can store and retrieve entities" --body "**Reference:** End of Week 2\n**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "priority:high,phase:1,component:infrastructure" --milestone "M1: HCG Store & Retrieve"
gh issue create --repo c-daly/logos --title "[D1] Architecture Decision Records (ADRs)" --body "**Epoch:** Epoch 1: Infrastructure & Knowledge Foundation" --label "type:documentation,priority:medium,phase:1" --milestone "M1: HCG Store & Retrieve"

# Epoch 2: Language & Perception Services
#  → M2: SHACL Validation

gh issue create --repo c-daly/logos --title "[A2] Implement SHACL validation" --body "**Reference:** Section 4.3.1\n**Workstream:** Workstream A: HCG Foundation and Validation\n**Epoch:** Epoch 2: Language & Perception Services\n
**Acceptance Criteria:**\n- [ ] Extend SHACL shapes for all entity types\n- [ ] Add relationship cardinality constraints\n- [ ] Add property datatype constraints\n- [ ] Create SHACL validation test suite (valid and invalid cases)\n- [ ] Integrate SHACL validation into Neo4j workflow" --label "workstream:A,component:infrastructure,priority:high,phase:1,type:testing" --milestone "M2: SHACL Validation"
gh issue create --repo c-daly/logos --title "[A3] Vector integration" --body "**Reference:** Section 4.2\n**Workstream:** Workstream A: HCG Foundation and Validation\n**Epoch:** Epoch 2: Language & Perception Services\n
**Acceptance Criteria:**\n- [ ] Design embedding schema in Milvus\n- [ ] Implement sync mechanism between Neo4j and Milvus\n- [ ] Add embedding_id properties to graph nodes\n- [ ] Create embedding generation pipeline (using Hermes)" --label "priority:high,workstream:A,phase:1,component:infrastructure" --milestone "M2: SHACL Validation"
gh issue create --repo c-daly/logos --title "[C1] Implement Hermes endpoints" --body "**Reference:** Section 3.4, Table 2\n**Workstream:** Workstream C: Hermes and Support Services\n**Epoch:** Epoch 2: Language & Perception Services\n
**Acceptance Criteria:**\n- [ ] `/stt` — Integrate Whisper or similar STT model\n- [ ] `/tts` — Integrate Coqui TTS or similar\n- [ ] `/simple_nlp` — Integrate spaCy for tokenization, POS, NER\n- [ ] `/embed_text` — Integrate sentence-transformers or OpenAI embeddings\n- [ ] Add request validation and error handling\n- [ ] Write API integration tests" --label "type:feature,component:hermes,priority:medium,workstream:C,phase:1" --milestone "M2: SHACL Validation"
gh issue create --repo c-daly/logos --title "[C2] Hermes deployment" --body "**Workstream:** Workstream C: Hermes and Support Services\n**Epoch:** Epoch 2: Language & Perception Services\n
**Acceptance Criteria:**\n- [ ] Create Dockerfile for Hermes\n- [ ] Add to docker-compose for local testing\n- [ ] Document API usage and examples\n- [ ] Set up health check endpoint" --label "component:hermes,priority:medium,workstream:C,phase:1" --milestone "M2: SHACL Validation"
gh issue create --repo c-daly/logos --title "[M2] SHACL validation catches errors" --body "**Reference:** End of Week 4\n**Epoch:** Epoch 2: Language & Perception Services" --label "priority:high,phase:1,type:testing,component:infrastructure" --milestone "M2: SHACL Validation"

# Epoch 3: Cognitive Core & Reasoning
#  → M3: Simple Planning

gh issue create --repo c-daly/logos --title "[B1] Orchestrator implementation" --body "**Reference:** Section 3.3\n**Workstream:** Workstream B: Sophia Cognitive Core Prototype\n**Epoch:** Epoch 3: Cognitive Core & Reasoning\n
**Acceptance Criteria:**\n- [ ] Design control flow state machine\n- [ ] Implement subsystem registration and lifecycle management\n- [ ] Add inter-subsystem message passing\n- [ ] Create Orchestrator integration tests" --label "type:feature,workstream:B,component:sophia,priority:high,phase:1" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[B2] CWM-A (Abstract World Model)" --body "**Reference:** Section 3.3\n**Workstream:** Workstream B: Sophia Cognitive Core Prototype\n**Epoch:** Epoch 3: Cognitive Core & Reasoning\n
**Acceptance Criteria:**\n- [ ] Design abstract state representation structure\n- [ ] Implement state update mechanism (read from HCG)\n- [ ] Implement state query API for Planner\n- [ ] Add state change event emission\n- [ ] Write unit tests for CWM-A" --label "priority:high,workstream:B,phase:1,component:sophia" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[B3] Planner (initial version)" --body "**Reference:** Section 3.3\n**Workstream:** Workstream B: Sophia Cognitive Core Prototype\n**Epoch:** Epoch 3: Cognitive Core & Reasoning\n
**Acceptance Criteria:**\n- [ ] Implement graph traversal-based planning\n- [ ] Define goal representation in HCG\n- [ ] Implement backward chaining from goal to current state\n- [ ] Generate action sequences (plans)\n- [ ] Add plan validation against SHACL constraints\n- [ ] Write planning test cases (simple scenarios)" --label "priority:high,workstream:B,phase:1,component:sophia" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[B4] Executor (stub)" --body "**Reference:** Section 3.3\n**Workstream:** Workstream B: Sophia Cognitive Core Prototype\n**Epoch:** Epoch 3: Cognitive Core & Reasoning\n
**Acceptance Criteria:**\n- [ ] Define execution interface (receive plans)\n- [ ] Implement plan step iteration\n- [ ] Add success/failure callback mechanism\n- [ ] Stub out Talos integration (simulated execution)" --label "priority:high,workstream:B,phase:1,component:sophia" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[C3] Talos simulated interfaces" --body "**Workstream:** Workstream C: Hermes and Support Services\n**Epoch:** Epoch 3: Cognitive Core & Reasoning\n
**Acceptance Criteria:**\n- [ ] Implement simulated sensor data generation\n- [ ] Implement simulated actuator command reception\n- [ ] Create \"pick and place\" scenario simulation\n- [ ] Add visualization of simulated environment (optional)" --label "priority:medium,workstream:C,phase:1,component:talos" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[C4] Apollo command interface (basic)" --body "**Workstream:** Workstream C: Hermes and Support Services\n**Epoch:** Epoch 3: Cognitive Core & Reasoning\n
**Acceptance Criteria:**\n- [ ] Create CLI tool for sending commands to Sophia\n- [ ] Add command history and logging\n- [ ] Display agent state and plan status\n- [ ] (Stretch) Add simple web UI" --label "component:apollo,workstream:C,priority:medium,phase:1" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[R1] Survey of causal reasoning methods" --body "**Epoch:** Epoch 3: Cognitive Core & Reasoning" --label "type:research,priority:low,phase:1" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[R2] Graph neural network integration" --body "**Epoch:** Epoch 3: Cognitive Core & Reasoning" --label "type:research,priority:low,phase:1" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[R3] Multi-modal grounding" --body "**Epoch:** Epoch 3: Cognitive Core & Reasoning" --label "type:research,priority:low,phase:1" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[M3] Sophia can plan simple actions" --body "**Reference:** End of Week 6\n**Epoch:** Epoch 3: Cognitive Core & Reasoning" --label "priority:high,phase:1,component:infrastructure" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[D2] Developer onboarding guide" --body "**Epoch:** Epoch 3: Cognitive Core & Reasoning" --label "type:documentation,priority:medium,phase:1" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[D3] API documentation" --body "**Epoch:** Epoch 3: Cognitive Core & Reasoning" --label "type:documentation,priority:medium,phase:1" --milestone "M3: Simple Planning"
gh issue create --repo c-daly/logos --title "[D4] Weekly progress reports" --body "**Epoch:** Epoch 3: Cognitive Core & Reasoning" --label "type:documentation,priority:medium,phase:1" --milestone "M3: Simple Planning"

# Epoch 4: Integration & Demonstration
#  → M4: Pick and Place

gh issue create --repo c-daly/logos --title "[B5] End-to-end integration" --body "**Workstream:** Workstream B: Sophia Cognitive Core Prototype\n**Epoch:** Epoch 4: Integration & Demonstration\n
**Acceptance Criteria:**\n- [ ] Wire up Orchestrator → CWM-A → Planner → Executor flow\n- [ ] Implement simple command: \"Pick up cup\"\n- [ ] Verify HCG updates occur correctly\n- [ ] Verify SHACL validation gates malformed updates" --label "priority:high,workstream:B,phase:1,component:sophia" --milestone "M4: Pick and Place"
gh issue create --repo c-daly/logos --title "[O1] Publish blog post" --body "**Epoch:** Epoch 4: Integration & Demonstration" --label "priority:low,type:outreach,phase:1" --milestone "M4: Pick and Place"
gh issue create --repo c-daly/logos --title "[O2] Create demo video" --body "**Epoch:** Epoch 4: Integration & Demonstration" --label "priority:low,type:feature,type:outreach,phase:1" --milestone "M4: Pick and Place"
gh issue create --repo c-daly/logos --title "[O3] Open-source release" --body "**Epoch:** Epoch 4: Integration & Demonstration" --label "priority:low,type:outreach,phase:1" --milestone "M4: Pick and Place"
gh issue create --repo c-daly/logos --title "[O4] Engage with research community" --body "**Epoch:** Epoch 4: Integration & Demonstration" --label "priority:low,type:outreach,phase:1" --milestone "M4: Pick and Place"
gh issue create --repo c-daly/logos --title "[M4] End-to-end \"pick and place\"" --body "**Reference:** End of Week 8\n**Epoch:** Epoch 4: Integration & Demonstration" --label "priority:high,phase:1,component:infrastructure" --milestone "M4: Pick and Place"
