# coding: utf-8

"""
    Hermes API

    Stateless language & embedding tools for Project LOGOS

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from logos_hermes_sdk.models.simple_nlp_response import SimpleNLPResponse

class TestSimpleNLPResponse(unittest.TestCase):
    """SimpleNLPResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimpleNLPResponse:
        """Test SimpleNLPResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SimpleNLPResponse`
        """
        model = SimpleNLPResponse()
        if include_optional:
            return SimpleNLPResponse(
                tokens = [
                    ''
                    ],
                pos_tags = [
                    logos_hermes_sdk.models.pos_tag.POSTag(
                        token = '', 
                        tag = '', )
                    ],
                lemmas = [
                    ''
                    ],
                entities = [
                    logos_hermes_sdk.models.entity.Entity(
                        text = '', 
                        label = '', 
                        start = 56, 
                        end = 56, )
                    ]
            )
        else:
            return SimpleNLPResponse(
        )
        """

    def testSimpleNLPResponse(self):
        """Test SimpleNLPResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
