# coding: utf-8

"""
    Hermes API

    Stateless language & embedding tools for Project LOGOS

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from logos_hermes_sdk.models.tts_request import TTSRequest

class TestTTSRequest(unittest.TestCase):
    """TTSRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TTSRequest:
        """Test TTSRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TTSRequest`
        """
        model = TTSRequest()
        if include_optional:
            return TTSRequest(
                text = '',
                voice = 'default',
                language = 'en-US'
            )
        else:
            return TTSRequest(
                text = '',
        )
        """

    def testTTSRequest(self):
        """Test TTSRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
