# coding: utf-8

"""
    Hermes API

    Stateless language & embedding tools for Project LOGOS

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from logos_hermes_sdk.models.llm_request import LLMRequest

class TestLLMRequest(unittest.TestCase):
    """LLMRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LLMRequest:
        """Test LLMRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LLMRequest`
        """
        model = LLMRequest()
        if include_optional:
            return LLMRequest(
                prompt = '',
                messages = [
                    logos_hermes_sdk.models.llm_message.LLMMessage(
                        role = 'system', 
                        content = '', 
                        name = '', )
                    ],
                provider = '',
                model = '',
                temperature = 0.0,
                max_tokens = 1.0,
                metadata = { }
            )
        else:
            return LLMRequest(
        )
        """

    def testLLMRequest(self):
        """Test LLMRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
