# coding: utf-8

"""
    Hermes API

    Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from logos_hermes_sdk.models.llm_choice import LLMChoice


class TestLLMChoice(unittest.TestCase):
    """LLMChoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LLMChoice:
        """Test LLMChoice
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LLMChoice`
        """
        model = LLMChoice()
        if include_optional:
            return LLMChoice(
                index = 56,
                message = logos_hermes_sdk.models.llm_message.LLMMessage(
                    role = 'system', 
                    content = '', 
                    name = '', ),
                finish_reason = ''
            )
        else:
            return LLMChoice(
                index = 56,
                message = logos_hermes_sdk.models.llm_message.LLMMessage(
                    role = 'system', 
                    content = '', 
                    name = '', ),
        )
        """

    def testLLMChoice(self):
        """Test LLMChoice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
