/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GeneratePlan200Response,
  GeneratePlanRequest,
  GetHealth200Response,
  GetState200Response,
  RunSimulation200Response,
  RunSimulationRequest,
} from '../models/index';
import {
    GeneratePlan200ResponseFromJSON,
    GeneratePlan200ResponseToJSON,
    GeneratePlanRequestFromJSON,
    GeneratePlanRequestToJSON,
    GetHealth200ResponseFromJSON,
    GetHealth200ResponseToJSON,
    GetState200ResponseFromJSON,
    GetState200ResponseToJSON,
    RunSimulation200ResponseFromJSON,
    RunSimulation200ResponseToJSON,
    RunSimulationRequestFromJSON,
    RunSimulationRequestToJSON,
} from '../models/index';

export interface GeneratePlanOperationRequest {
    generatePlanRequest: GeneratePlanRequest;
}

export interface GetStateRequest {
    cursor?: string;
    limit?: number;
    modelType?: GetStateModelTypeEnum;
    status?: GetStateStatusEnum;
    tags?: Array<string>;
}

export interface RunSimulationOperationRequest {
    runSimulationRequest: RunSimulationRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Accepts a goal structure, reads from Neo4j, runs the planner, and returns a process graph with simulation predictions. 
     * Generate Plan
     */
    async generatePlanRaw(requestParameters: GeneratePlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeneratePlan200Response>> {
        if (requestParameters['generatePlanRequest'] == null) {
            throw new runtime.RequiredError(
                'generatePlanRequest',
                'Required parameter "generatePlanRequest" was null or undefined when calling generatePlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/plan`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GeneratePlanRequestToJSON(requestParameters['generatePlanRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeneratePlan200ResponseFromJSON(jsonValue));
    }

    /**
     * Accepts a goal structure, reads from Neo4j, runs the planner, and returns a process graph with simulation predictions. 
     * Generate Plan
     */
    async generatePlan(requestParameters: GeneratePlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeneratePlan200Response> {
        const response = await this.generatePlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns health status of Sophia service and its dependencies
     * Health Check
     */
    async getHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHealth200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHealth200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns health status of Sophia service and its dependencies
     * Health Check
     */
    async getHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHealth200Response> {
        const response = await this.getHealthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns the latest entity states, persona metadata, and diagnostic information for Apollo and other clients. Supports pagination via cursor. 
     * Get Current State
     */
    async getStateRaw(requestParameters: GetStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetState200Response>> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['modelType'] != null) {
            queryParameters['model_type'] = requestParameters['modelType'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/state`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetState200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the latest entity states, persona metadata, and diagnostic information for Apollo and other clients. Supports pagination via cursor. 
     * Get Current State
     */
    async getState(requestParameters: GetStateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetState200Response> {
        const response = await this.getStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Triggers CWM-G to perform short-horizon predictions. Results are tagged as imagined:true in Neo4j. Accepts capability_id and context with entity references, sensor frames, and optional Talos metadata. 
     * Run Simulation
     */
    async runSimulationRaw(requestParameters: RunSimulationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RunSimulation200Response>> {
        if (requestParameters['runSimulationRequest'] == null) {
            throw new runtime.RequiredError(
                'runSimulationRequest',
                'Required parameter "runSimulationRequest" was null or undefined when calling runSimulation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/simulate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunSimulationRequestToJSON(requestParameters['runSimulationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunSimulation200ResponseFromJSON(jsonValue));
    }

    /**
     * Triggers CWM-G to perform short-horizon predictions. Results are tagged as imagined:true in Neo4j. Accepts capability_id and context with entity references, sensor frames, and optional Talos metadata. 
     * Run Simulation
     */
    async runSimulation(requestParameters: RunSimulationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RunSimulation200Response> {
        const response = await this.runSimulationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetStateModelTypeEnum = {
    CwmA: 'CWM_A',
    CwmG: 'CWM_G',
    CwmE: 'CWM_E'
} as const;
export type GetStateModelTypeEnum = typeof GetStateModelTypeEnum[keyof typeof GetStateModelTypeEnum];
/**
 * @export
 */
export const GetStateStatusEnum = {
    Observed: 'observed',
    Imagined: 'imagined',
    Reflected: 'reflected'
} as const;
export type GetStateStatusEnum = typeof GetStateStatusEnum[keyof typeof GetStateStatusEnum];
