# coding: utf-8

# flake8: noqa

"""
    Hermes API

    Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "EmbedText200Response",
    "EmbedTextRequest",
    "LLMChoice",
    "LLMMessage",
    "LLMRequest",
    "LLMResponse",
    "LLMUsage",
    "SimpleNlp200Response",
    "SimpleNlp200ResponseEntitiesInner",
    "SimpleNlp200ResponsePosTagsInner",
    "SimpleNlpRequest",
    "SpeechToText200Response",
    "TextToSpeechRequest",
]

# import apis into sdk package
from logos_hermes_sdk.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from logos_hermes_sdk.api_response import ApiResponse as ApiResponse
from logos_hermes_sdk.api_client import ApiClient as ApiClient
from logos_hermes_sdk.configuration import Configuration as Configuration
from logos_hermes_sdk.exceptions import OpenApiException as OpenApiException
from logos_hermes_sdk.exceptions import ApiTypeError as ApiTypeError
from logos_hermes_sdk.exceptions import ApiValueError as ApiValueError
from logos_hermes_sdk.exceptions import ApiKeyError as ApiKeyError
from logos_hermes_sdk.exceptions import ApiAttributeError as ApiAttributeError
from logos_hermes_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from logos_hermes_sdk.models.embed_text200_response import (
    EmbedText200Response as EmbedText200Response,
)
from logos_hermes_sdk.models.embed_text_request import (
    EmbedTextRequest as EmbedTextRequest,
)
from logos_hermes_sdk.models.llm_choice import LLMChoice as LLMChoice
from logos_hermes_sdk.models.llm_message import LLMMessage as LLMMessage
from logos_hermes_sdk.models.llm_request import LLMRequest as LLMRequest
from logos_hermes_sdk.models.llm_response import LLMResponse as LLMResponse
from logos_hermes_sdk.models.llm_usage import LLMUsage as LLMUsage
from logos_hermes_sdk.models.simple_nlp200_response import (
    SimpleNlp200Response as SimpleNlp200Response,
)
from logos_hermes_sdk.models.simple_nlp200_response_entities_inner import (
    SimpleNlp200ResponseEntitiesInner as SimpleNlp200ResponseEntitiesInner,
)
from logos_hermes_sdk.models.simple_nlp200_response_pos_tags_inner import (
    SimpleNlp200ResponsePosTagsInner as SimpleNlp200ResponsePosTagsInner,
)
from logos_hermes_sdk.models.simple_nlp_request import (
    SimpleNlpRequest as SimpleNlpRequest,
)
from logos_hermes_sdk.models.speech_to_text200_response import (
    SpeechToText200Response as SpeechToText200Response,
)
from logos_hermes_sdk.models.text_to_speech_request import (
    TextToSpeechRequest as TextToSpeechRequest,
)
