# coding: utf-8

"""
Sophia API

Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/architecture/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data.

The version of the OpenAPI document: 0.2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from logos_sophia_sdk.models.plan_request import PlanRequest


class TestPlanRequest(unittest.TestCase):
    """PlanRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanRequest:
        """Test PlanRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PlanRequest`
        """
        model = PlanRequest()
        if include_optional:
            return PlanRequest(
                goal = '',
                context = { },
                constraints = [
                    ''
                    ],
                priority = 'P1',
                metadata = { }
            )
        else:
            return PlanRequest(
                goal = '',
        )
        """

    def testPlanRequest(self):
        """Test PlanRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
