# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from logos_sophia_sdk.models.cwmg_imagined_data import CWMGImaginedData

class TestCWMGImaginedData(unittest.TestCase):
    """CWMGImaginedData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CWMGImaginedData:
        """Test CWMGImaginedData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CWMGImaginedData`
        """
        model = CWMGImaginedData()
        if include_optional:
            return CWMGImaginedData(
                imagined = True,
                horizon_steps = 56,
                frames = [
                    ''
                    ],
                embeddings = [
                    1.337
                    ],
                assumptions = [
                    ''
                    ]
            )
        else:
            return CWMGImaginedData(
        )
        """

    def testCWMGImaginedData(self):
        """Test CWMGImaginedData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
