# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/architecture/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from logos_sophia_sdk.models.simulation_response import SimulationResponse

class TestSimulationResponse(unittest.TestCase):
    """SimulationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimulationResponse:
        """Test SimulationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SimulationResponse`
        """
        model = SimulationResponse()
        if include_optional:
            return SimulationResponse(
                simulation_id = '',
                status = 'completed',
                duration_ms = 56,
                states = [
                    logos_sophia_sdk.models.cwm_state.CWMState(
                        state_id = '', 
                        model_type = 'CWM_A', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        data = { }, )
                    ]
            )
        else:
            return SimulationResponse(
                simulation_id = '',
                status = 'completed',
                states = [
                    logos_sophia_sdk.models.cwm_state.CWMState(
                        state_id = '', 
                        model_type = 'CWM_A', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        data = { }, )
                    ],
        )
        """

    def testSimulationResponse(self):
        """Test SimulationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
