# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/architecture/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class CWMState(BaseModel):
    """
    Unified causal world model state envelope (thin transport wrapper). All meaningful metadata (provenance) lives in `data`, not on the envelope. This is a breaking change from the previous schema which had provenance on the envelope. 
    """ # noqa: E501
    state_id: StrictStr = Field(description="Globally unique identifier (`cwm_<model>_<uuid>`)")
    model_type: StrictStr
    timestamp: datetime = Field(description="When the response was generated")
    data: Dict[str, Any] = Field(description="Verbatim node properties including provenance. Contains: - source: Module/job that created it (e.g., jepa_runner, planner) - derivation: How derived (observed, imagined, reflected) - confidence: 0.0-1.0 certainty score (optional) - created: ISO8601 timestamp when node was created - updated: ISO8601 timestamp when node was last modified - tags: Free-form labels (array of strings) - links: Related entity IDs (object with process_ids, plan_id, entity_ids, etc.) - Plus model-specific content (entities, relations for CWM-A; etc.) ")
    __properties: ClassVar[List[str]] = ["state_id", "model_type", "timestamp", "data"]

    @field_validator('model_type')
    def model_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CWM_A', 'CWM_G', 'CWM_E']):
            raise ValueError("must be one of enum values ('CWM_A', 'CWM_G', 'CWM_E')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CWMState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CWMState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "state_id": obj.get("state_id"),
            "model_type": obj.get("model_type"),
            "timestamp": obj.get("timestamp"),
            "data": obj.get("data")
        })
        return _obj


