name: Documentation Task
description: Documentation or knowledge management task
title: "[Docs] "
labels: ["type:documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Documentation or knowledge management task
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Task priority level
      options:
        - priority:critical
        - priority:high
        - priority:medium
        - priority:low
    validations:
      required: true
  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: Type of documentation
      options:
        - Architecture Decision Record (ADR)
        - Developer Guide
        - API Documentation
        - Tutorial
        - Other
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What exists today, why this matters
      placeholder: Describe the current state and motivation
    validations:
      required: true
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What "done" looks like
      placeholder: Describe the desired end state
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Constraints, related issues, links to design docs
      placeholder: Optional additional context
    validations:
      required: false
