name: Sophia Task
description: Task related to Sophia cognitive core component
title: "[Sophia] "
labels: ["component:sophia"]
body:
  - type: markdown
    attributes:
      value: |
        Task for the Sophia cognitive core component (Orchestrator, CWM-A, CWM-G, Planner, Executor)
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Task priority level
      options:
        - priority:critical
        - priority:high
        - priority:medium
        - priority:low
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What exists today, why this matters
      placeholder: Describe the current state and motivation
    validations:
      required: true
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What "done" looks like
      placeholder: Describe the desired end state
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Specific, verifiable criteria for completion
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Constraints, related issues, links to design docs
      placeholder: Optional additional context
    validations:
      required: false
