name: Sophia Task
description: Task related to Sophia cognitive core component
title: "[Sophia] "
labels: ["component:sophia"]
body:
  - type: markdown
    attributes:
      value: |
        Task for the Sophia cognitive core component (Orchestrator, CWM-A, CWM-G, Planner, Executor)
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Task priority level
      options:
        - priority:high
        - priority:medium
        - priority:low
    validations:
      required: true
  - type: dropdown
    id: workstream
    attributes:
      label: Workstream
      description: Associated workstream
      options:
        - Workstream B - Sophia Cognitive Core Prototype
        - Other
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Detailed description of the task
      placeholder: Describe what needs to be done
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Tasks or components this depends on
      placeholder: List any dependencies
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What defines completion of this task?
      placeholder: List acceptance criteria
    validations:
      required: false
