# coding: utf-8

# flake8: noqa
"""
    Hermes API

    Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from logos_hermes_sdk.models.embed_text200_response import EmbedText200Response
from logos_hermes_sdk.models.embed_text_request import EmbedTextRequest
from logos_hermes_sdk.models.llm_choice import LLMChoice
from logos_hermes_sdk.models.llm_message import LLMMessage
from logos_hermes_sdk.models.llm_request import LLMRequest
from logos_hermes_sdk.models.llm_response import LLMResponse
from logos_hermes_sdk.models.llm_usage import LLMUsage
from logos_hermes_sdk.models.simple_nlp200_response import SimpleNlp200Response
from logos_hermes_sdk.models.simple_nlp200_response_entities_inner import SimpleNlp200ResponseEntitiesInner
from logos_hermes_sdk.models.simple_nlp200_response_pos_tags_inner import SimpleNlp200ResponsePosTagsInner
from logos_hermes_sdk.models.simple_nlp_request import SimpleNlpRequest
from logos_hermes_sdk.models.speech_to_text200_response import SpeechToText200Response
from logos_hermes_sdk.models.text_to_speech_request import TextToSpeechRequest

