# coding: utf-8

"""
    Hermes API

    Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation - LLM gateway proxy via `/llm`  All endpoints are stateless and do not interact with the HCG directly. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from logos_hermes_sdk.models.simple_nlp200_response_entities_inner import SimpleNlp200ResponseEntitiesInner
from logos_hermes_sdk.models.simple_nlp200_response_pos_tags_inner import SimpleNlp200ResponsePosTagsInner
from typing import Optional, Set
from typing_extensions import Self

class SimpleNlp200Response(BaseModel):
    """
    SimpleNlp200Response
    """ # noqa: E501
    tokens: Optional[List[StrictStr]] = Field(default=None, description="Tokenized text (if requested)")
    pos_tags: Optional[List[SimpleNlp200ResponsePosTagsInner]] = Field(default=None, description="POS tags (if requested)")
    lemmas: Optional[List[StrictStr]] = Field(default=None, description="Lemmatized tokens (if requested)")
    entities: Optional[List[SimpleNlp200ResponseEntitiesInner]] = Field(default=None, description="Named entities (if requested)")
    __properties: ClassVar[List[str]] = ["tokens", "pos_tags", "lemmas", "entities"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SimpleNlp200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pos_tags (list)
        _items = []
        if self.pos_tags:
            for _item_pos_tags in self.pos_tags:
                if _item_pos_tags:
                    _items.append(_item_pos_tags.to_dict())
            _dict['pos_tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in entities (list)
        _items = []
        if self.entities:
            for _item_entities in self.entities:
                if _item_entities:
                    _items.append(_item_entities.to_dict())
            _dict['entities'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SimpleNlp200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tokens": obj.get("tokens"),
            "pos_tags": [SimpleNlp200ResponsePosTagsInner.from_dict(_item) for _item in obj["pos_tags"]] if obj.get("pos_tags") is not None else None,
            "lemmas": obj.get("lemmas"),
            "entities": [SimpleNlp200ResponseEntitiesInner.from_dict(_item) for _item in obj["entities"]] if obj.get("entities") is not None else None
        })
        return _obj


