# LOGOS Ecosystem Test Stack Configuration
#
# Port allocation standard: base_port + repo_offset
#   hermes:  +10000
#   apollo:  +20000
#   logos:   +30000
#   sophia:  +40000
#   talos:   +50000
#
# Base ports:
#   Neo4j HTTP: 7474, Bolt: 7687
#   Milvus gRPC: 19530, Metrics: 9091
#   MinIO API: 9000, Console: 9001
#   API: 8000
#
# See logos_config.ports for the single source of truth.

defaults:
  compose_filename: docker-compose.test.yml
  env_filename: .env.test
  path: .
  context:
    service_prefix: logos-test
    volume_prefix: logos_test
    network_name: logos-test-network
    neo4j_version: "5.14.0"
    neo4j_username: neo4j
    neo4j_password: neo4jtest
    neo4j_http_port: "7474"
    neo4j_bolt_port: "7687"
    etcd_version: "v3.5.15"
    minio_version: "RELEASE.2024-11-07T00-52-20Z"
    minio_root_user: minioadmin
    minio_root_password: minioadmin
    minio_api_port: "9000"
    minio_console_port: "9001"
    milvus_version: "v2.4.15"
    milvus_grpc_port: "19530"
    milvus_metrics_port: "9091"
  env:
    NEO4J_URI: "bolt://neo4j:{neo4j_bolt_port}"
    NEO4J_USER: "{neo4j_username}"
    NEO4J_PASSWORD: "{neo4j_password}"
    MILVUS_HOST: milvus
    MILVUS_PORT: "{milvus_grpc_port}"
    MILVUS_HEALTHCHECK: "http://milvus:{milvus_metrics_port}/healthz"

repos:
  # hermes: +10000 offset (Milvus only, no Neo4j)
  hermes:
    path: ../hermes
    service_prefix: hermes-test
    volume_prefix: hermes_test
    services:
      - milvus-etcd
      - milvus-minio
      - milvus
    context:
      milvus_grpc_port: "29530"
      milvus_metrics_port: "19091"
      minio_api_port: "19000"
      minio_console_port: "19001"
    env:
      MILVUS_HOST: milvus
      MILVUS_PORT: "{milvus_grpc_port}"

  # apollo: +20000 offset
  apollo:
    path: ../apollo
    service_prefix: apollo-test
    volume_prefix: apollo_test
    services:
      - neo4j
      - milvus-etcd
      - milvus-minio
      - milvus
    context:
      neo4j_http_port: "27474"
      neo4j_bolt_port: "27687"
      milvus_grpc_port: "39530"
      milvus_metrics_port: "29091"
      minio_api_port: "29000"
      minio_console_port: "29001"
    env:
      NEO4J_URI: "bolt://neo4j:{neo4j_bolt_port}"

  # logos: +30000 offset
  logos:
    path: .
    service_prefix: logos-test
    volume_prefix: logos_test
    network_name: logos-test-network
    services:
      - neo4j
      - milvus-etcd
      - milvus-minio
      - milvus
    context:
      neo4j_http_port: "37474"
      neo4j_bolt_port: "37687"
      milvus_grpc_port: "49530"
      milvus_metrics_port: "39091"
      minio_api_port: "39000"
      minio_console_port: "39001"
    env:
      NEO4J_URI: "bolt://neo4j:{neo4j_bolt_port}"

  # sophia: +40000 offset
  sophia:
    path: ../sophia
    service_prefix: sophia-test
    volume_prefix: sophia_test
    services:
      - neo4j
      - milvus-etcd
      - milvus-minio
      - milvus
    context:
      neo4j_http_port: "47474"
      neo4j_bolt_port: "47687"
      milvus_grpc_port: "59530"
      milvus_metrics_port: "49091"
      minio_api_port: "49000"
      minio_console_port: "49001"
    env:
      NEO4J_URI: "bolt://neo4j:{neo4j_bolt_port}"

  # talos: +50000 offset
  talos:
    path: ../talos
    service_prefix: talos-test
    volume_prefix: talos_test
    services:
      - neo4j
      - milvus-etcd
      - milvus-minio
      - milvus
    context:
      neo4j_http_port: "57474"
      neo4j_bolt_port: "57687"
      milvus_grpc_port: "69530"
      milvus_metrics_port: "59091"
      minio_api_port: "59000"
      minio_console_port: "59001"
    env:
      NEO4J_URI: "bolt://neo4j:{neo4j_bolt_port}"
