# LOGOS Ecosystem Test Stack Configuration
#
# Port values are sourced from logos_config.ports (single source of truth).
# Do NOT hardcode ports here - they are injected by render_test_stacks.py.
#
# Port allocation standard: base_port + repo_offset
#   hermes:  +10000
#   apollo:  +20000
#   logos:   +30000
#   sophia:  +40000
#   talos:   +50000

defaults:
  compose_filename: docker-compose.test.yml
  env_filename: .env.test
  path: .
  context:
    service_prefix: logos-test
    volume_prefix: logos_test
    network_name: logos-test-network
    neo4j_version: "5.14.0"
    neo4j_username: neo4j
    neo4j_password: neo4jtest
    etcd_version: "v3.5.15"
    minio_version: "RELEASE.2024-11-07T00-52-20Z"
    minio_root_user: minioadmin
    minio_root_password: minioadmin
    milvus_version: "v2.4.15"
  env:
    NEO4J_URI: "bolt://neo4j:{neo4j_bolt_port}"
    NEO4J_USER: "{neo4j_username}"
    NEO4J_PASSWORD: "{neo4j_password}"
    MILVUS_HOST: milvus
    MILVUS_PORT: "{milvus_grpc_port}"
    MILVUS_HEALTHCHECK: "http://milvus:{milvus_metrics_port}/healthz"

repos:
  # hermes: +10000 offset (Milvus only, no Neo4j)
  # Ports from logos_config.HERMES_PORTS
  hermes:
    path: ../hermes
    service_prefix: hermes-test
    volume_prefix: hermes_test
    services:
      - milvus-etcd
      - milvus-minio
      - milvus
    env:
      MILVUS_HOST: milvus
      MILVUS_PORT: "{milvus_grpc_port}"

  # apollo: +20000 offset
  # Ports from logos_config.APOLLO_PORTS
  apollo:
    path: ../apollo
    service_prefix: apollo-test
    volume_prefix: apollo_test
    services:
      - neo4j
      - milvus-etcd
      - milvus-minio
      - milvus
    env:
      NEO4J_URI: "bolt://neo4j:{neo4j_bolt_port}"

  # logos: +30000 offset
  # Ports from logos_config.LOGOS_PORTS
  logos:
    path: .
    service_prefix: logos-test
    volume_prefix: logos_test
    network_name: logos-test-network
    services:
      - neo4j
      - milvus-etcd
      - milvus-minio
      - milvus
    env:
      NEO4J_URI: "bolt://neo4j:{neo4j_bolt_port}"

  # sophia: +40000 offset
  # Ports from logos_config.SOPHIA_PORTS
  sophia:
    path: ../sophia
    service_prefix: sophia-test
    volume_prefix: sophia_test
    services:
      - neo4j
      - milvus-etcd
      - milvus-minio
      - milvus
    env:
      NEO4J_URI: "bolt://neo4j:{neo4j_bolt_port}"

  # talos: +50000 offset
  # Ports from logos_config.TALOS_PORTS
  talos:
    path: ../talos
    service_prefix: talos-test
    volume_prefix: talos_test
    services:
      - neo4j
      - milvus-etcd
      - milvus-minio
      - milvus
    env:
      NEO4J_URI: "bolt://neo4j:{neo4j_bolt_port}"
