/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StateResponse,
} from '../models/index';
import {
    StateResponseFromJSON,
    StateResponseToJSON,
} from '../models/index';

export interface GetStateRequest {
    cursor?: string;
    limit?: number;
    modelType?: GetStateModelTypeEnum;
}

/**
 * 
 */
export class WorldModelApi extends runtime.BaseAPI {

    /**
     * Returns the latest persisted CWM states. Supports pagination cursors and optional filtering. 
     * Stream world-model state
     */
    async getStateRaw(requestParameters: GetStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateResponse>> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['modelType'] != null) {
            queryParameters['model_type'] = requestParameters['modelType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/state`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StateResponseFromJSON(jsonValue));
    }

    /**
     * Returns the latest persisted CWM states. Supports pagination cursors and optional filtering. 
     * Stream world-model state
     */
    async getState(requestParameters: GetStateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateResponse> {
        const response = await this.getStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetStateModelTypeEnum = {
    CwmA: 'CWM_A',
    CwmG: 'CWM_G',
    CwmE: 'CWM_E'
} as const;
export type GetStateModelTypeEnum = typeof GetStateModelTypeEnum[keyof typeof GetStateModelTypeEnum];
