# coding: utf-8

"""
    Hermes API

    Canonical Hermes OpenAPI contract for Project LOGOS. See Project LOGOS spec: Table 2 in Section 3.4 (Hermes API endpoints).  Hermes is the stateless language & embedding utility providing: - Speech-to-text (STT) - Text-to-speech (TTS) - Simple NLP preprocessing - Text embedding generation  All endpoints are stateless and do not interact with the HCG directly. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hermes_client.models.simple_nlp200_response import SimpleNlp200Response

class TestSimpleNlp200Response(unittest.TestCase):
    """SimpleNlp200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimpleNlp200Response:
        """Test SimpleNlp200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SimpleNlp200Response`
        """
        model = SimpleNlp200Response()
        if include_optional:
            return SimpleNlp200Response(
                tokens = [
                    ''
                    ],
                pos_tags = [
                    hermes_client.models.simple_nlp_200_response_pos_tags_inner.simpleNlp_200_response_pos_tags_inner(
                        token = '', 
                        tag = '', )
                    ],
                lemmas = [
                    ''
                    ],
                entities = [
                    hermes_client.models.simple_nlp_200_response_entities_inner.simpleNlp_200_response_entities_inner(
                        text = '', 
                        label = '', 
                        start = 56, 
                        end = 56, )
                    ]
            )
        else:
            return SimpleNlp200Response(
        )
        """

    def testSimpleNlp200Response(self):
        """Test SimpleNlp200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
