/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CWMAGraphDataValidation } from './CWMAGraphDataValidation';
import {
    CWMAGraphDataValidationFromJSON,
    CWMAGraphDataValidationFromJSONTyped,
    CWMAGraphDataValidationToJSON,
    CWMAGraphDataValidationToJSONTyped,
} from './CWMAGraphDataValidation';

/**
 * Payload for CWM-A (abstract reasoning) outputs.
 * @export
 * @interface CWMAGraphData
 */
export interface CWMAGraphData {
    /**
     * Normalized entity diffs
     * @type {Array<object>}
     * @memberof CWMAGraphData
     */
    entities?: Array<object>;
    /**
     * Relationship diffs
     * @type {Array<object>}
     * @memberof CWMAGraphData
     */
    relations?: Array<object>;
    /**
     * SHACL validation issues, if any
     * @type {Array<string>}
     * @memberof CWMAGraphData
     */
    violations?: Array<string>;
    /**
     * 
     * @type {CWMAGraphDataValidation}
     * @memberof CWMAGraphData
     */
    validation?: CWMAGraphDataValidation;
}

/**
 * Check if a given object implements the CWMAGraphData interface.
 */
export function instanceOfCWMAGraphData(value: object): value is CWMAGraphData {
    return true;
}

export function CWMAGraphDataFromJSON(json: any): CWMAGraphData {
    return CWMAGraphDataFromJSONTyped(json, false);
}

export function CWMAGraphDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CWMAGraphData {
    if (json == null) {
        return json;
    }
    return {
        
        'entities': json['entities'] == null ? undefined : json['entities'],
        'relations': json['relations'] == null ? undefined : json['relations'],
        'violations': json['violations'] == null ? undefined : json['violations'],
        'validation': json['validation'] == null ? undefined : CWMAGraphDataValidationFromJSON(json['validation']),
    };
}

export function CWMAGraphDataToJSON(json: any): CWMAGraphData {
    return CWMAGraphDataToJSONTyped(json, false);
}

export function CWMAGraphDataToJSONTyped(value?: CWMAGraphData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entities': value['entities'],
        'relations': value['relations'],
        'violations': value['violations'],
        'validation': CWMAGraphDataValidationToJSON(value['validation']),
    };
}

