/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CWMAGraphDataValidation
 */
export interface CWMAGraphDataValidation {
    /**
     * 
     * @type {string}
     * @memberof CWMAGraphDataValidation
     */
    status?: CWMAGraphDataValidationStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CWMAGraphDataValidation
     */
    message?: string;
}


/**
 * @export
 */
export const CWMAGraphDataValidationStatusEnum = {
    Passed: 'passed',
    Failed: 'failed'
} as const;
export type CWMAGraphDataValidationStatusEnum = typeof CWMAGraphDataValidationStatusEnum[keyof typeof CWMAGraphDataValidationStatusEnum];


/**
 * Check if a given object implements the CWMAGraphDataValidation interface.
 */
export function instanceOfCWMAGraphDataValidation(value: object): value is CWMAGraphDataValidation {
    return true;
}

export function CWMAGraphDataValidationFromJSON(json: any): CWMAGraphDataValidation {
    return CWMAGraphDataValidationFromJSONTyped(json, false);
}

export function CWMAGraphDataValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CWMAGraphDataValidation {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CWMAGraphDataValidationToJSON(json: any): CWMAGraphDataValidation {
    return CWMAGraphDataValidationToJSONTyped(json, false);
}

export function CWMAGraphDataValidationToJSONTyped(value?: CWMAGraphDataValidation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

