/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payload for CWM-E (persona/emotion) outputs.
 * @export
 * @interface CWMESentimentData
 */
export interface CWMESentimentData {
    /**
     * e.g., confident, cautious
     * @type {string}
     * @memberof CWMESentimentData
     */
    sentiment?: string;
    /**
     * 
     * @type {number}
     * @memberof CWMESentimentData
     */
    confidenceDelta?: number;
    /**
     * 
     * @type {number}
     * @memberof CWMESentimentData
     */
    cautionDelta?: number;
    /**
     * Short diary-style reflection
     * @type {string}
     * @memberof CWMESentimentData
     */
    narrative?: string;
}

/**
 * Check if a given object implements the CWMESentimentData interface.
 */
export function instanceOfCWMESentimentData(value: object): value is CWMESentimentData {
    return true;
}

export function CWMESentimentDataFromJSON(json: any): CWMESentimentData {
    return CWMESentimentDataFromJSONTyped(json, false);
}

export function CWMESentimentDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CWMESentimentData {
    if (json == null) {
        return json;
    }
    return {
        
        'sentiment': json['sentiment'] == null ? undefined : json['sentiment'],
        'confidenceDelta': json['confidence_delta'] == null ? undefined : json['confidence_delta'],
        'cautionDelta': json['caution_delta'] == null ? undefined : json['caution_delta'],
        'narrative': json['narrative'] == null ? undefined : json['narrative'],
    };
}

export function CWMESentimentDataToJSON(json: any): CWMESentimentData {
    return CWMESentimentDataToJSONTyped(json, false);
}

export function CWMESentimentDataToJSONTyped(value?: CWMESentimentData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sentiment': value['sentiment'],
        'confidence_delta': value['confidenceDelta'],
        'caution_delta': value['cautionDelta'],
        'narrative': value['narrative'],
    };
}

