/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payload for CWM-G (grounded/JEPA) outputs.
 * @export
 * @interface CWMGImaginedData
 */
export interface CWMGImaginedData {
    /**
     * 
     * @type {boolean}
     * @memberof CWMGImaginedData
     */
    imagined?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CWMGImaginedData
     */
    horizonSteps?: number;
    /**
     * URIs or identifiers for imagined frames
     * @type {Array<string>}
     * @memberof CWMGImaginedData
     */
    frames?: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof CWMGImaginedData
     */
    embeddings?: Array<number>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CWMGImaginedData
     */
    assumptions?: Array<string>;
}

/**
 * Check if a given object implements the CWMGImaginedData interface.
 */
export function instanceOfCWMGImaginedData(value: object): value is CWMGImaginedData {
    return true;
}

export function CWMGImaginedDataFromJSON(json: any): CWMGImaginedData {
    return CWMGImaginedDataFromJSONTyped(json, false);
}

export function CWMGImaginedDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CWMGImaginedData {
    if (json == null) {
        return json;
    }
    return {
        
        'imagined': json['imagined'] == null ? undefined : json['imagined'],
        'horizonSteps': json['horizon_steps'] == null ? undefined : json['horizon_steps'],
        'frames': json['frames'] == null ? undefined : json['frames'],
        'embeddings': json['embeddings'] == null ? undefined : json['embeddings'],
        'assumptions': json['assumptions'] == null ? undefined : json['assumptions'],
    };
}

export function CWMGImaginedDataToJSON(json: any): CWMGImaginedData {
    return CWMGImaginedDataToJSONTyped(json, false);
}

export function CWMGImaginedDataToJSONTyped(value?: CWMGImaginedData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imagined': value['imagined'],
        'horizon_steps': value['horizonSteps'],
        'frames': value['frames'],
        'embeddings': value['embeddings'],
        'assumptions': value['assumptions'],
    };
}

