/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CWMStateLinks } from './CWMStateLinks';
import {
    CWMStateLinksFromJSON,
    CWMStateLinksFromJSONTyped,
    CWMStateLinksToJSON,
    CWMStateLinksToJSONTyped,
} from './CWMStateLinks';
import type { CWMStateData } from './CWMStateData';
import {
    CWMStateDataFromJSON,
    CWMStateDataFromJSONTyped,
    CWMStateDataToJSON,
    CWMStateDataToJSONTyped,
} from './CWMStateData';

/**
 * Unified causal world model state envelope.
 * @export
 * @interface CWMState
 */
export interface CWMState {
    /**
     * Globally unique identifier (`cwm_<model>_<uuid>`)
     * @type {string}
     * @memberof CWMState
     */
    stateId: string;
    /**
     * 
     * @type {string}
     * @memberof CWMState
     */
    modelType: CWMStateModelTypeEnum;
    /**
     * Subsystem that emitted the record (e.g., orchestrator, jepa_runner)
     * @type {string}
     * @memberof CWMState
     */
    source: string;
    /**
     * 
     * @type {Date}
     * @memberof CWMState
     */
    timestamp: Date;
    /**
     * 
     * @type {number}
     * @memberof CWMState
     */
    confidence: number;
    /**
     * 
     * @type {string}
     * @memberof CWMState
     */
    status: CWMStateStatusEnum;
    /**
     * 
     * @type {CWMStateLinks}
     * @memberof CWMState
     */
    links: CWMStateLinks;
    /**
     * Free-form labels for diagnostics filtering
     * @type {Array<string>}
     * @memberof CWMState
     */
    tags?: Array<string>;
    /**
     * 
     * @type {CWMStateData}
     * @memberof CWMState
     */
    data: CWMStateData;
}


/**
 * @export
 */
export const CWMStateModelTypeEnum = {
    CwmA: 'CWM_A',
    CwmG: 'CWM_G',
    CwmE: 'CWM_E'
} as const;
export type CWMStateModelTypeEnum = typeof CWMStateModelTypeEnum[keyof typeof CWMStateModelTypeEnum];

/**
 * @export
 */
export const CWMStateStatusEnum = {
    Observed: 'observed',
    Imagined: 'imagined',
    Reflected: 'reflected',
    Ephemeral: 'ephemeral'
} as const;
export type CWMStateStatusEnum = typeof CWMStateStatusEnum[keyof typeof CWMStateStatusEnum];


/**
 * Check if a given object implements the CWMState interface.
 */
export function instanceOfCWMState(value: object): value is CWMState {
    if (!('stateId' in value) || value['stateId'] === undefined) return false;
    if (!('modelType' in value) || value['modelType'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CWMStateFromJSON(json: any): CWMState {
    return CWMStateFromJSONTyped(json, false);
}

export function CWMStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CWMState {
    if (json == null) {
        return json;
    }
    return {
        
        'stateId': json['state_id'],
        'modelType': json['model_type'],
        'source': json['source'],
        'timestamp': (new Date(json['timestamp'])),
        'confidence': json['confidence'],
        'status': json['status'],
        'links': CWMStateLinksFromJSON(json['links']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'data': CWMStateDataFromJSON(json['data']),
    };
}

export function CWMStateToJSON(json: any): CWMState {
    return CWMStateToJSONTyped(json, false);
}

export function CWMStateToJSONTyped(value?: CWMState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state_id': value['stateId'],
        'model_type': value['modelType'],
        'source': value['source'],
        'timestamp': value['timestamp'].toISOString(),
        'confidence': value['confidence'],
        'status': value['status'],
        'links': CWMStateLinksToJSON(value['links']),
        'tags': value['tags'],
        'data': CWMStateDataToJSON(value['data']),
    };
}

