/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CWMAGraphData } from './CWMAGraphData';
import {
    instanceOfCWMAGraphData,
    CWMAGraphDataFromJSON,
    CWMAGraphDataFromJSONTyped,
    CWMAGraphDataToJSON,
} from './CWMAGraphData';
import type { CWMESentimentData } from './CWMESentimentData';
import {
    instanceOfCWMESentimentData,
    CWMESentimentDataFromJSON,
    CWMESentimentDataFromJSONTyped,
    CWMESentimentDataToJSON,
} from './CWMESentimentData';
import type { CWMGImaginedData } from './CWMGImaginedData';
import {
    instanceOfCWMGImaginedData,
    CWMGImaginedDataFromJSON,
    CWMGImaginedDataFromJSONTyped,
    CWMGImaginedDataToJSON,
} from './CWMGImaginedData';

/**
 * @type CWMStateData
 * Model-specific payload
 * @export
 */
export type CWMStateData = CWMAGraphData | CWMESentimentData | CWMGImaginedData;

export function CWMStateDataFromJSON(json: any): CWMStateData {
    return CWMStateDataFromJSONTyped(json, false);
}

export function CWMStateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CWMStateData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCWMAGraphData(json)) {
        return CWMAGraphDataFromJSONTyped(json, true);
    }
    if (instanceOfCWMESentimentData(json)) {
        return CWMESentimentDataFromJSONTyped(json, true);
    }
    if (instanceOfCWMGImaginedData(json)) {
        return CWMGImaginedDataFromJSONTyped(json, true);
    }
    return {} as any;
}

export function CWMStateDataToJSON(json: any): any {
    return CWMStateDataToJSONTyped(json, false);
}

export function CWMStateDataToJSONTyped(value?: CWMStateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCWMAGraphData(value)) {
        return CWMAGraphDataToJSON(value as CWMAGraphData);
    }
    if (instanceOfCWMESentimentData(value)) {
        return CWMESentimentDataToJSON(value as CWMESentimentData);
    }
    if (instanceOfCWMGImaginedData(value)) {
        return CWMGImaginedDataToJSON(value as CWMGImaginedData);
    }
    return {};
}

