/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/architecture/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Unified causal world model state envelope (thin transport wrapper).
 * All meaningful metadata (provenance) lives in `data`, not on the envelope.
 * This is a breaking change from the previous schema which had provenance on the envelope.
 * 
 * @export
 * @interface CWMState
 */
export interface CWMState {
    /**
     * Globally unique identifier (`cwm_<model>_<uuid>`)
     * @type {string}
     * @memberof CWMState
     */
    stateId: string;
    /**
     * 
     * @type {string}
     * @memberof CWMState
     */
    modelType: CWMStateModelTypeEnum;
    /**
     * When the response was generated
     * @type {Date}
     * @memberof CWMState
     */
    timestamp: Date;
    /**
     * Verbatim node properties including provenance. Contains:
     * - source: Module/job that created it (e.g., jepa_runner, planner)
     * - derivation: How derived (observed, imagined, reflected)
     * - confidence: 0.0-1.0 certainty score (optional)
     * - created: ISO8601 timestamp when node was created
     * - updated: ISO8601 timestamp when node was last modified
     * - tags: Free-form labels (array of strings)
     * - links: Related entity IDs (object with process_ids, plan_id, entity_ids, etc.)
     * - Plus model-specific content (entities, relations for CWM-A; etc.)
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CWMState
     */
    data: { [key: string]: any; };
}


/**
 * @export
 */
export const CWMStateModelTypeEnum = {
    CwmA: 'CWM_A',
    CwmG: 'CWM_G',
    CwmE: 'CWM_E'
} as const;
export type CWMStateModelTypeEnum = typeof CWMStateModelTypeEnum[keyof typeof CWMStateModelTypeEnum];


/**
 * Check if a given object implements the CWMState interface.
 */
export function instanceOfCWMState(value: object): value is CWMState {
    if (!('stateId' in value) || value['stateId'] === undefined) return false;
    if (!('modelType' in value) || value['modelType'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CWMStateFromJSON(json: any): CWMState {
    return CWMStateFromJSONTyped(json, false);
}

export function CWMStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CWMState {
    if (json == null) {
        return json;
    }
    return {
        
        'stateId': json['state_id'],
        'modelType': json['model_type'],
        'timestamp': (new Date(json['timestamp'])),
        'data': json['data'],
    };
}

export function CWMStateToJSON(json: any): CWMState {
    return CWMStateToJSONTyped(json, false);
}

export function CWMStateToJSONTyped(value?: CWMState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state_id': value['stateId'],
        'model_type': value['modelType'],
        'timestamp': value['timestamp'].toISOString(),
        'data': value['data'],
    };
}

