/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CWMStateLinks
 */
export interface CWMStateLinks {
    /**
     * 
     * @type {Array<string>}
     * @memberof CWMStateLinks
     */
    processIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CWMStateLinks
     */
    planId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CWMStateLinks
     */
    entityIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CWMStateLinks
     */
    mediaSampleId?: string;
    /**
     * 
     * @type {string}
     * @memberof CWMStateLinks
     */
    personaEntryId?: string;
    /**
     * 
     * @type {string}
     * @memberof CWMStateLinks
     */
    talosRunId?: string;
}

/**
 * Check if a given object implements the CWMStateLinks interface.
 */
export function instanceOfCWMStateLinks(value: object): value is CWMStateLinks {
    return true;
}

export function CWMStateLinksFromJSON(json: any): CWMStateLinks {
    return CWMStateLinksFromJSONTyped(json, false);
}

export function CWMStateLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): CWMStateLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'processIds': json['process_ids'] == null ? undefined : json['process_ids'],
        'planId': json['plan_id'] == null ? undefined : json['plan_id'],
        'entityIds': json['entity_ids'] == null ? undefined : json['entity_ids'],
        'mediaSampleId': json['media_sample_id'] == null ? undefined : json['media_sample_id'],
        'personaEntryId': json['persona_entry_id'] == null ? undefined : json['persona_entry_id'],
        'talosRunId': json['talos_run_id'] == null ? undefined : json['talos_run_id'],
    };
}

export function CWMStateLinksToJSON(json: any): CWMStateLinks {
    return CWMStateLinksToJSONTyped(json, false);
}

export function CWMStateLinksToJSONTyped(value?: CWMStateLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'process_ids': value['processIds'],
        'plan_id': value['planId'],
        'entity_ids': value['entityIds'],
        'media_sample_id': value['mediaSampleId'],
        'persona_entry_id': value['personaEntryId'],
        'talos_run_id': value['talosRunId'],
    };
}

