/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanRequest
 */
export interface PlanRequest {
    /**
     * Natural-language goal or structured identifier
     * @type {string}
     * @memberof PlanRequest
     */
    goal: string;
    /**
     * Optional context (entities, constraints, media references)
     * @type {{ [key: string]: any; }}
     * @memberof PlanRequest
     */
    context?: { [key: string]: any; };
    /**
     * Hard constraints the planner must honor
     * @type {Array<string>}
     * @memberof PlanRequest
     */
    constraints?: Array<string>;
    /**
     * Informational priority label (e.g., P0/P1/P2)
     * @type {string}
     * @memberof PlanRequest
     */
    priority?: string;
    /**
     * Arbitrary metadata for downstream audits
     * @type {{ [key: string]: any; }}
     * @memberof PlanRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the PlanRequest interface.
 */
export function instanceOfPlanRequest(value: object): value is PlanRequest {
    if (!('goal' in value) || value['goal'] === undefined) return false;
    return true;
}

export function PlanRequestFromJSON(json: any): PlanRequest {
    return PlanRequestFromJSONTyped(json, false);
}

export function PlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'goal': json['goal'],
        'context': json['context'] == null ? undefined : json['context'],
        'constraints': json['constraints'] == null ? undefined : json['constraints'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function PlanRequestToJSON(json: any): PlanRequest {
    return PlanRequestToJSONTyped(json, false);
}

export function PlanRequestToJSONTyped(value?: PlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'goal': value['goal'],
        'context': value['context'],
        'constraints': value['constraints'],
        'priority': value['priority'],
        'metadata': value['metadata'],
    };
}

