/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CWMState } from './CWMState';
import {
    CWMStateFromJSON,
    CWMStateFromJSONTyped,
    CWMStateToJSON,
    CWMStateToJSONTyped,
} from './CWMState';

/**
 * 
 * @export
 * @interface PlanResponse
 */
export interface PlanResponse {
    /**
     * Identifier of the persisted plan
     * @type {string}
     * @memberof PlanResponse
     */
    planId?: string;
    /**
     * Planner status at response time
     * @type {string}
     * @memberof PlanResponse
     */
    status?: PlanResponseStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof PlanResponse
     */
    submittedAt?: Date;
    /**
     * Human-readable planning notes or warnings
     * @type {Array<string>}
     * @memberof PlanResponse
     */
    diagnostics?: Array<string>;
    /**
     * World-model states (observed + imagined) generated by this request
     * @type {Array<CWMState>}
     * @memberof PlanResponse
     */
    states?: Array<CWMState>;
}


/**
 * @export
 */
export const PlanResponseStatusEnum = {
    Accepted: 'accepted',
    InProgress: 'in_progress',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type PlanResponseStatusEnum = typeof PlanResponseStatusEnum[keyof typeof PlanResponseStatusEnum];


/**
 * Check if a given object implements the PlanResponse interface.
 */
export function instanceOfPlanResponse(value: object): value is PlanResponse {
    return true;
}

export function PlanResponseFromJSON(json: any): PlanResponse {
    return PlanResponseFromJSONTyped(json, false);
}

export function PlanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'planId': json['plan_id'] == null ? undefined : json['plan_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'submittedAt': json['submitted_at'] == null ? undefined : (new Date(json['submitted_at'])),
        'diagnostics': json['diagnostics'] == null ? undefined : json['diagnostics'],
        'states': json['states'] == null ? undefined : ((json['states'] as Array<any>).map(CWMStateFromJSON)),
    };
}

export function PlanResponseToJSON(json: any): PlanResponse {
    return PlanResponseToJSONTyped(json, false);
}

export function PlanResponseToJSONTyped(value?: PlanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plan_id': value['planId'],
        'status': value['status'],
        'submitted_at': value['submittedAt'] == null ? value['submittedAt'] : value['submittedAt'].toISOString(),
        'diagnostics': value['diagnostics'],
        'states': value['states'] == null ? undefined : ((value['states'] as Array<any>).map(CWMStateToJSON)),
    };
}

