/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/architecture/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Goal specification with description and target_state
 * @export
 * @interface PlanRequestGoal
 */
export interface PlanRequestGoal {
    /**
     * Natural-language description of the goal
     * @type {string}
     * @memberof PlanRequestGoal
     */
    description: string;
    /**
     * Identifier for the desired target state
     * @type {string}
     * @memberof PlanRequestGoal
     */
    targetState: string;
}

/**
 * Check if a given object implements the PlanRequestGoal interface.
 */
export function instanceOfPlanRequestGoal(value: object): value is PlanRequestGoal {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('targetState' in value) || value['targetState'] === undefined) return false;
    return true;
}

export function PlanRequestGoalFromJSON(json: any): PlanRequestGoal {
    return PlanRequestGoalFromJSONTyped(json, false);
}

export function PlanRequestGoalFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanRequestGoal {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'targetState': json['target_state'],
    };
}

export function PlanRequestGoalToJSON(json: any): PlanRequestGoal {
    return PlanRequestGoalToJSONTyped(json, false);
}

export function PlanRequestGoalToJSONTyped(value?: PlanRequestGoal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'target_state': value['targetState'],
    };
}

