/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CWMState } from './CWMState';
import {
    CWMStateFromJSON,
    CWMStateFromJSONTyped,
    CWMStateToJSON,
    CWMStateToJSONTyped,
} from './CWMState';

/**
 * 
 * @export
 * @interface SimulationResponse
 */
export interface SimulationResponse {
    /**
     * 
     * @type {string}
     * @memberof SimulationResponse
     */
    simulationId: string;
    /**
     * 
     * @type {string}
     * @memberof SimulationResponse
     */
    status: SimulationResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof SimulationResponse
     */
    durationMs?: number;
    /**
     * 
     * @type {Array<CWMState>}
     * @memberof SimulationResponse
     */
    states: Array<CWMState>;
}


/**
 * @export
 */
export const SimulationResponseStatusEnum = {
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type SimulationResponseStatusEnum = typeof SimulationResponseStatusEnum[keyof typeof SimulationResponseStatusEnum];


/**
 * Check if a given object implements the SimulationResponse interface.
 */
export function instanceOfSimulationResponse(value: object): value is SimulationResponse {
    if (!('simulationId' in value) || value['simulationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('states' in value) || value['states'] === undefined) return false;
    return true;
}

export function SimulationResponseFromJSON(json: any): SimulationResponse {
    return SimulationResponseFromJSONTyped(json, false);
}

export function SimulationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'simulationId': json['simulation_id'],
        'status': json['status'],
        'durationMs': json['duration_ms'] == null ? undefined : json['duration_ms'],
        'states': ((json['states'] as Array<any>).map(CWMStateFromJSON)),
    };
}

export function SimulationResponseToJSON(json: any): SimulationResponse {
    return SimulationResponseToJSONTyped(json, false);
}

export function SimulationResponseToJSONTyped(value?: SimulationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simulation_id': value['simulationId'],
        'status': value['status'],
        'duration_ms': value['durationMs'],
        'states': ((value['states'] as Array<any>).map(CWMStateToJSON)),
    };
}

