/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulationRequest
 */
export interface SimulationRequest {
    /**
     * Capability or Talos action identifier
     * @type {string}
     * @memberof SimulationRequest
     */
    capabilityId: string;
    /**
     * Structured context (entity IDs, sensor frames, parameters)
     * @type {{ [key: string]: any; }}
     * @memberof SimulationRequest
     */
    context: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof SimulationRequest
     */
    horizonSteps?: number;
    /**
     * Optional assumptions applied to the rollout
     * @type {Array<string>}
     * @memberof SimulationRequest
     */
    assumptions?: Array<string>;
    /**
     * Miscellaneous metadata for audit trails
     * @type {{ [key: string]: any; }}
     * @memberof SimulationRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SimulationRequest interface.
 */
export function instanceOfSimulationRequest(value: object): value is SimulationRequest {
    if (!('capabilityId' in value) || value['capabilityId'] === undefined) return false;
    if (!('context' in value) || value['context'] === undefined) return false;
    return true;
}

export function SimulationRequestFromJSON(json: any): SimulationRequest {
    return SimulationRequestFromJSONTyped(json, false);
}

export function SimulationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'capabilityId': json['capability_id'],
        'context': json['context'],
        'horizonSteps': json['horizon_steps'] == null ? undefined : json['horizon_steps'],
        'assumptions': json['assumptions'] == null ? undefined : json['assumptions'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function SimulationRequestToJSON(json: any): SimulationRequest {
    return SimulationRequestToJSONTyped(json, false);
}

export function SimulationRequestToJSONTyped(value?: SimulationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capability_id': value['capabilityId'],
        'context': value['context'],
        'horizon_steps': value['horizonSteps'],
        'assumptions': value['assumptions'],
        'metadata': value['metadata'],
    };
}

