/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/phase2/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CWMState } from './CWMState';
import {
    CWMStateFromJSON,
    CWMStateFromJSONTyped,
    CWMStateToJSON,
    CWMStateToJSONTyped,
} from './CWMState';

/**
 * 
 * @export
 * @interface StateResponse
 */
export interface StateResponse {
    /**
     * 
     * @type {Array<CWMState>}
     * @memberof StateResponse
     */
    states: Array<CWMState>;
    /**
     * Cursor for retrieving the next page
     * @type {string}
     * @memberof StateResponse
     */
    cursor?: string;
    /**
     * Suggested wait time before polling again
     * @type {number}
     * @memberof StateResponse
     */
    nextPollAfterMs?: number;
}

/**
 * Check if a given object implements the StateResponse interface.
 */
export function instanceOfStateResponse(value: object): value is StateResponse {
    if (!('states' in value) || value['states'] === undefined) return false;
    return true;
}

export function StateResponseFromJSON(json: any): StateResponse {
    return StateResponseFromJSONTyped(json, false);
}

export function StateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'states': ((json['states'] as Array<any>).map(CWMStateFromJSON)),
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'nextPollAfterMs': json['next_poll_after_ms'] == null ? undefined : json['next_poll_after_ms'],
    };
}

export function StateResponseToJSON(json: any): StateResponse {
    return StateResponseToJSONTyped(json, false);
}

export function StateResponseToJSONTyped(value?: StateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'states': ((value['states'] as Array<any>).map(CWMStateToJSON)),
        'cursor': value['cursor'],
        'next_poll_after_ms': value['nextPollAfterMs'],
    };
}

