/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CWMStateLinks } from './CWMStateLinks';
import {
    CWMStateLinksFromJSON,
    CWMStateLinksFromJSONTyped,
    CWMStateLinksToJSON,
    CWMStateLinksToJSONTyped,
} from './CWMStateLinks';

/**
 * Unified Causal World Model State envelope. All world-model emissions
 * (CWM-A, CWM-G, CWM-E) serialize to this structure.
 * 
 * @export
 * @interface CWMState
 */
export interface CWMState {
    /**
     * Globally unique identifier (cwm_<model>_<uuid>)
     * @type {string}
     * @memberof CWMState
     */
    stateId: string;
    /**
     * Which CWM model produced this state
     * @type {string}
     * @memberof CWMState
     */
    modelType: CWMStateModelTypeEnum;
    /**
     * Subsystem that produced the record (e.g., orchestrator, jepa_runner)
     * @type {string}
     * @memberof CWMState
     */
    source: string;
    /**
     * ISO-8601 UTC time the state became valid
     * @type {Date}
     * @memberof CWMState
     */
    timestamp: Date;
    /**
     * Certainty score (JEPA probability, validation score, etc.)
     * @type {number}
     * @memberof CWMState
     */
    confidence: number;
    /**
     * Distinguishes real-time telemetry from simulations/reflections
     * @type {string}
     * @memberof CWMState
     */
    status: CWMStateStatusEnum;
    /**
     * 
     * @type {CWMStateLinks}
     * @memberof CWMState
     */
    links?: CWMStateLinks;
    /**
     * Free-form labels for filtering (e.g., capability:perception)
     * @type {Array<string>}
     * @memberof CWMState
     */
    tags?: Array<string>;
    /**
     * Model-specific payload
     * @type {{ [key: string]: any; }}
     * @memberof CWMState
     */
    data?: { [key: string]: any; };
}


/**
 * @export
 */
export const CWMStateModelTypeEnum = {
    CwmA: 'CWM_A',
    CwmG: 'CWM_G',
    CwmE: 'CWM_E'
} as const;
export type CWMStateModelTypeEnum = typeof CWMStateModelTypeEnum[keyof typeof CWMStateModelTypeEnum];

/**
 * @export
 */
export const CWMStateStatusEnum = {
    Observed: 'observed',
    Imagined: 'imagined',
    Reflected: 'reflected'
} as const;
export type CWMStateStatusEnum = typeof CWMStateStatusEnum[keyof typeof CWMStateStatusEnum];


/**
 * Check if a given object implements the CWMState interface.
 */
export function instanceOfCWMState(value: object): value is CWMState {
    if (!('stateId' in value) || value['stateId'] === undefined) return false;
    if (!('modelType' in value) || value['modelType'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CWMStateFromJSON(json: any): CWMState {
    return CWMStateFromJSONTyped(json, false);
}

export function CWMStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CWMState {
    if (json == null) {
        return json;
    }
    return {
        
        'stateId': json['state_id'],
        'modelType': json['model_type'],
        'source': json['source'],
        'timestamp': (new Date(json['timestamp'])),
        'confidence': json['confidence'],
        'status': json['status'],
        'links': json['links'] == null ? undefined : CWMStateLinksFromJSON(json['links']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function CWMStateToJSON(json: any): CWMState {
    return CWMStateToJSONTyped(json, false);
}

export function CWMStateToJSONTyped(value?: CWMState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state_id': value['stateId'],
        'model_type': value['modelType'],
        'source': value['source'],
        'timestamp': value['timestamp'].toISOString(),
        'confidence': value['confidence'],
        'status': value['status'],
        'links': CWMStateLinksToJSON(value['links']),
        'tags': value['tags'],
        'data': value['data'],
    };
}

