/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneratePlanRequestGoalStateEntitiesInner
 */
export interface GeneratePlanRequestGoalStateEntitiesInner {
    /**
     * 
     * @type {string}
     * @memberof GeneratePlanRequestGoalStateEntitiesInner
     */
    entityId?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratePlanRequestGoalStateEntitiesInner
     */
    desiredState?: string;
}

/**
 * Check if a given object implements the GeneratePlanRequestGoalStateEntitiesInner interface.
 */
export function instanceOfGeneratePlanRequestGoalStateEntitiesInner(value: object): value is GeneratePlanRequestGoalStateEntitiesInner {
    return true;
}

export function GeneratePlanRequestGoalStateEntitiesInnerFromJSON(json: any): GeneratePlanRequestGoalStateEntitiesInner {
    return GeneratePlanRequestGoalStateEntitiesInnerFromJSONTyped(json, false);
}

export function GeneratePlanRequestGoalStateEntitiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePlanRequestGoalStateEntitiesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'entityId': json['entity_id'] == null ? undefined : json['entity_id'],
        'desiredState': json['desired_state'] == null ? undefined : json['desired_state'],
    };
}

export function GeneratePlanRequestGoalStateEntitiesInnerToJSON(json: any): GeneratePlanRequestGoalStateEntitiesInner {
    return GeneratePlanRequestGoalStateEntitiesInnerToJSONTyped(json, false);
}

export function GeneratePlanRequestGoalStateEntitiesInnerToJSONTyped(value?: GeneratePlanRequestGoalStateEntitiesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity_id': value['entityId'],
        'desired_state': value['desiredState'],
    };
}

