/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneratePlan200ResponseProcessesInner
 */
export interface GeneratePlan200ResponseProcessesInner {
    /**
     * 
     * @type {string}
     * @memberof GeneratePlan200ResponseProcessesInner
     */
    processId?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratePlan200ResponseProcessesInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratePlan200ResponseProcessesInner
     */
    capabilityId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeneratePlan200ResponseProcessesInner
     */
    preconditions?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeneratePlan200ResponseProcessesInner
     */
    effects?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof GeneratePlan200ResponseProcessesInner
     */
    estimatedDuration?: number;
}

/**
 * Check if a given object implements the GeneratePlan200ResponseProcessesInner interface.
 */
export function instanceOfGeneratePlan200ResponseProcessesInner(value: object): value is GeneratePlan200ResponseProcessesInner {
    return true;
}

export function GeneratePlan200ResponseProcessesInnerFromJSON(json: any): GeneratePlan200ResponseProcessesInner {
    return GeneratePlan200ResponseProcessesInnerFromJSONTyped(json, false);
}

export function GeneratePlan200ResponseProcessesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePlan200ResponseProcessesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'processId': json['process_id'] == null ? undefined : json['process_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'capabilityId': json['capability_id'] == null ? undefined : json['capability_id'],
        'preconditions': json['preconditions'] == null ? undefined : json['preconditions'],
        'effects': json['effects'] == null ? undefined : json['effects'],
        'estimatedDuration': json['estimated_duration'] == null ? undefined : json['estimated_duration'],
    };
}

export function GeneratePlan200ResponseProcessesInnerToJSON(json: any): GeneratePlan200ResponseProcessesInner {
    return GeneratePlan200ResponseProcessesInnerToJSONTyped(json, false);
}

export function GeneratePlan200ResponseProcessesInnerToJSONTyped(value?: GeneratePlan200ResponseProcessesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'process_id': value['processId'],
        'name': value['name'],
        'capability_id': value['capabilityId'],
        'preconditions': value['preconditions'],
        'effects': value['effects'],
        'estimated_duration': value['estimatedDuration'],
    };
}

