/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneratePlan200ResponseCausalLinksInner
 */
export interface GeneratePlan200ResponseCausalLinksInner {
    /**
     * 
     * @type {string}
     * @memberof GeneratePlan200ResponseCausalLinksInner
     */
    fromProcess?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratePlan200ResponseCausalLinksInner
     */
    toProcess?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratePlan200ResponseCausalLinksInner
     */
    condition?: string;
}

/**
 * Check if a given object implements the GeneratePlan200ResponseCausalLinksInner interface.
 */
export function instanceOfGeneratePlan200ResponseCausalLinksInner(value: object): value is GeneratePlan200ResponseCausalLinksInner {
    return true;
}

export function GeneratePlan200ResponseCausalLinksInnerFromJSON(json: any): GeneratePlan200ResponseCausalLinksInner {
    return GeneratePlan200ResponseCausalLinksInnerFromJSONTyped(json, false);
}

export function GeneratePlan200ResponseCausalLinksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePlan200ResponseCausalLinksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'fromProcess': json['from_process'] == null ? undefined : json['from_process'],
        'toProcess': json['to_process'] == null ? undefined : json['to_process'],
        'condition': json['condition'] == null ? undefined : json['condition'],
    };
}

export function GeneratePlan200ResponseCausalLinksInnerToJSON(json: any): GeneratePlan200ResponseCausalLinksInner {
    return GeneratePlan200ResponseCausalLinksInnerToJSONTyped(json, false);
}

export function GeneratePlan200ResponseCausalLinksInnerToJSONTyped(value?: GeneratePlan200ResponseCausalLinksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from_process': value['fromProcess'],
        'to_process': value['toProcess'],
        'condition': value['condition'],
    };
}

