/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneratePlan200ResponseProcessesInner } from './GeneratePlan200ResponseProcessesInner';
import {
    GeneratePlan200ResponseProcessesInnerFromJSON,
    GeneratePlan200ResponseProcessesInnerFromJSONTyped,
    GeneratePlan200ResponseProcessesInnerToJSON,
    GeneratePlan200ResponseProcessesInnerToJSONTyped,
} from './GeneratePlan200ResponseProcessesInner';
import type { CWMState } from './CWMState';
import {
    CWMStateFromJSON,
    CWMStateFromJSONTyped,
    CWMStateToJSON,
    CWMStateToJSONTyped,
} from './CWMState';
import type { GeneratePlan200ResponseCausalLinksInner } from './GeneratePlan200ResponseCausalLinksInner';
import {
    GeneratePlan200ResponseCausalLinksInnerFromJSON,
    GeneratePlan200ResponseCausalLinksInnerFromJSONTyped,
    GeneratePlan200ResponseCausalLinksInnerToJSON,
    GeneratePlan200ResponseCausalLinksInnerToJSONTyped,
} from './GeneratePlan200ResponseCausalLinksInner';

/**
 * 
 * @export
 * @interface GeneratePlan200Response
 */
export interface GeneratePlan200Response {
    /**
     * Unique identifier for the generated plan
     * @type {string}
     * @memberof GeneratePlan200Response
     */
    planId?: string;
    /**
     * 
     * @type {Array<GeneratePlan200ResponseProcessesInner>}
     * @memberof GeneratePlan200Response
     */
    processes?: Array<GeneratePlan200ResponseProcessesInner>;
    /**
     * 
     * @type {Array<GeneratePlan200ResponseCausalLinksInner>}
     * @memberof GeneratePlan200Response
     */
    causalLinks?: Array<GeneratePlan200ResponseCausalLinksInner>;
    /**
     * Newly created CWMState records from planning
     * @type {Array<CWMState>}
     * @memberof GeneratePlan200Response
     */
    cwmStates?: Array<CWMState>;
    /**
     * Overall plan confidence (0.0 to 1.0)
     * @type {number}
     * @memberof GeneratePlan200Response
     */
    confidence?: number;
}

/**
 * Check if a given object implements the GeneratePlan200Response interface.
 */
export function instanceOfGeneratePlan200Response(value: object): value is GeneratePlan200Response {
    return true;
}

export function GeneratePlan200ResponseFromJSON(json: any): GeneratePlan200Response {
    return GeneratePlan200ResponseFromJSONTyped(json, false);
}

export function GeneratePlan200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePlan200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'planId': json['plan_id'] == null ? undefined : json['plan_id'],
        'processes': json['processes'] == null ? undefined : ((json['processes'] as Array<any>).map(GeneratePlan200ResponseProcessesInnerFromJSON)),
        'causalLinks': json['causal_links'] == null ? undefined : ((json['causal_links'] as Array<any>).map(GeneratePlan200ResponseCausalLinksInnerFromJSON)),
        'cwmStates': json['cwm_states'] == null ? undefined : ((json['cwm_states'] as Array<any>).map(CWMStateFromJSON)),
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
    };
}

export function GeneratePlan200ResponseToJSON(json: any): GeneratePlan200Response {
    return GeneratePlan200ResponseToJSONTyped(json, false);
}

export function GeneratePlan200ResponseToJSONTyped(value?: GeneratePlan200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plan_id': value['planId'],
        'processes': value['processes'] == null ? undefined : ((value['processes'] as Array<any>).map(GeneratePlan200ResponseProcessesInnerToJSON)),
        'causal_links': value['causalLinks'] == null ? undefined : ((value['causalLinks'] as Array<any>).map(GeneratePlan200ResponseCausalLinksInnerToJSON)),
        'cwm_states': value['cwmStates'] == null ? undefined : ((value['cwmStates'] as Array<any>).map(CWMStateToJSON)),
        'confidence': value['confidence'],
    };
}

