/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneratePlanRequestGoalStateEntitiesInner } from './GeneratePlanRequestGoalStateEntitiesInner';
import {
    GeneratePlanRequestGoalStateEntitiesInnerFromJSON,
    GeneratePlanRequestGoalStateEntitiesInnerFromJSONTyped,
    GeneratePlanRequestGoalStateEntitiesInnerToJSON,
    GeneratePlanRequestGoalStateEntitiesInnerToJSONTyped,
} from './GeneratePlanRequestGoalStateEntitiesInner';

/**
 * Target state specification
 * @export
 * @interface GeneratePlanRequestGoalState
 */
export interface GeneratePlanRequestGoalState {
    /**
     * 
     * @type {Array<GeneratePlanRequestGoalStateEntitiesInner>}
     * @memberof GeneratePlanRequestGoalState
     */
    entities?: Array<GeneratePlanRequestGoalStateEntitiesInner>;
}

/**
 * Check if a given object implements the GeneratePlanRequestGoalState interface.
 */
export function instanceOfGeneratePlanRequestGoalState(value: object): value is GeneratePlanRequestGoalState {
    return true;
}

export function GeneratePlanRequestGoalStateFromJSON(json: any): GeneratePlanRequestGoalState {
    return GeneratePlanRequestGoalStateFromJSONTyped(json, false);
}

export function GeneratePlanRequestGoalStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePlanRequestGoalState {
    if (json == null) {
        return json;
    }
    return {
        
        'entities': json['entities'] == null ? undefined : ((json['entities'] as Array<any>).map(GeneratePlanRequestGoalStateEntitiesInnerFromJSON)),
    };
}

export function GeneratePlanRequestGoalStateToJSON(json: any): GeneratePlanRequestGoalState {
    return GeneratePlanRequestGoalStateToJSONTyped(json, false);
}

export function GeneratePlanRequestGoalStateToJSONTyped(value?: GeneratePlanRequestGoalState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entities': value['entities'] == null ? undefined : ((value['entities'] as Array<any>).map(GeneratePlanRequestGoalStateEntitiesInnerToJSON)),
    };
}

