/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetHealth200ResponseMilvus } from './GetHealth200ResponseMilvus';
import {
    GetHealth200ResponseMilvusFromJSON,
    GetHealth200ResponseMilvusFromJSONTyped,
    GetHealth200ResponseMilvusToJSON,
    GetHealth200ResponseMilvusToJSONTyped,
} from './GetHealth200ResponseMilvus';
import type { GetHealth200ResponseNeo4j } from './GetHealth200ResponseNeo4j';
import {
    GetHealth200ResponseNeo4jFromJSON,
    GetHealth200ResponseNeo4jFromJSONTyped,
    GetHealth200ResponseNeo4jToJSON,
    GetHealth200ResponseNeo4jToJSONTyped,
} from './GetHealth200ResponseNeo4j';

/**
 * 
 * @export
 * @interface GetHealth200Response
 */
export interface GetHealth200Response {
    /**
     * 
     * @type {string}
     * @memberof GetHealth200Response
     */
    status?: GetHealth200ResponseStatusEnum;
    /**
     * 
     * @type {GetHealth200ResponseNeo4j}
     * @memberof GetHealth200Response
     */
    neo4j?: GetHealth200ResponseNeo4j;
    /**
     * 
     * @type {GetHealth200ResponseMilvus}
     * @memberof GetHealth200Response
     */
    milvus?: GetHealth200ResponseMilvus;
    /**
     * 
     * @type {Date}
     * @memberof GetHealth200Response
     */
    timestamp?: Date;
}


/**
 * @export
 */
export const GetHealth200ResponseStatusEnum = {
    Healthy: 'healthy',
    Degraded: 'degraded',
    Unhealthy: 'unhealthy'
} as const;
export type GetHealth200ResponseStatusEnum = typeof GetHealth200ResponseStatusEnum[keyof typeof GetHealth200ResponseStatusEnum];


/**
 * Check if a given object implements the GetHealth200Response interface.
 */
export function instanceOfGetHealth200Response(value: object): value is GetHealth200Response {
    return true;
}

export function GetHealth200ResponseFromJSON(json: any): GetHealth200Response {
    return GetHealth200ResponseFromJSONTyped(json, false);
}

export function GetHealth200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealth200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'neo4j': json['neo4j'] == null ? undefined : GetHealth200ResponseNeo4jFromJSON(json['neo4j']),
        'milvus': json['milvus'] == null ? undefined : GetHealth200ResponseMilvusFromJSON(json['milvus']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function GetHealth200ResponseToJSON(json: any): GetHealth200Response {
    return GetHealth200ResponseToJSONTyped(json, false);
}

export function GetHealth200ResponseToJSONTyped(value?: GetHealth200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'neo4j': GetHealth200ResponseNeo4jToJSON(value['neo4j']),
        'milvus': GetHealth200ResponseMilvusToJSON(value['milvus']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
    };
}

