/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHealth200ResponseMilvus
 */
export interface GetHealth200ResponseMilvus {
    /**
     * 
     * @type {boolean}
     * @memberof GetHealth200ResponseMilvus
     */
    connected?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetHealth200ResponseMilvus
     */
    collections?: Array<string>;
}

/**
 * Check if a given object implements the GetHealth200ResponseMilvus interface.
 */
export function instanceOfGetHealth200ResponseMilvus(value: object): value is GetHealth200ResponseMilvus {
    return true;
}

export function GetHealth200ResponseMilvusFromJSON(json: any): GetHealth200ResponseMilvus {
    return GetHealth200ResponseMilvusFromJSONTyped(json, false);
}

export function GetHealth200ResponseMilvusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealth200ResponseMilvus {
    if (json == null) {
        return json;
    }
    return {
        
        'connected': json['connected'] == null ? undefined : json['connected'],
        'collections': json['collections'] == null ? undefined : json['collections'],
    };
}

export function GetHealth200ResponseMilvusToJSON(json: any): GetHealth200ResponseMilvus {
    return GetHealth200ResponseMilvusToJSONTyped(json, false);
}

export function GetHealth200ResponseMilvusToJSONTyped(value?: GetHealth200ResponseMilvus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connected': value['connected'],
        'collections': value['collections'],
    };
}

