/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CWMState } from './CWMState';
import {
    CWMStateFromJSON,
    CWMStateFromJSONTyped,
    CWMStateToJSON,
    CWMStateToJSONTyped,
} from './CWMState';

/**
 * 
 * @export
 * @interface GetState200Response
 */
export interface GetState200Response {
    /**
     * 
     * @type {Array<CWMState>}
     * @memberof GetState200Response
     */
    states?: Array<CWMState>;
    /**
     * Cursor for next page (null if no more results)
     * @type {string}
     * @memberof GetState200Response
     */
    cursor?: string;
    /**
     * Total number of states matching filters
     * @type {number}
     * @memberof GetState200Response
     */
    total?: number;
}

/**
 * Check if a given object implements the GetState200Response interface.
 */
export function instanceOfGetState200Response(value: object): value is GetState200Response {
    return true;
}

export function GetState200ResponseFromJSON(json: any): GetState200Response {
    return GetState200ResponseFromJSONTyped(json, false);
}

export function GetState200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetState200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'states': json['states'] == null ? undefined : ((json['states'] as Array<any>).map(CWMStateFromJSON)),
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function GetState200ResponseToJSON(json: any): GetState200Response {
    return GetState200ResponseToJSONTyped(json, false);
}

export function GetState200ResponseToJSONTyped(value?: GetState200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'states': value['states'] == null ? undefined : ((value['states'] as Array<any>).map(CWMStateToJSON)),
        'cursor': value['cursor'],
        'total': value['total'],
    };
}

