/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Simulation context
 * @export
 * @interface RunSimulationRequestContext
 */
export interface RunSimulationRequestContext {
    /**
     * Entity references for simulation
     * @type {Array<string>}
     * @memberof RunSimulationRequestContext
     */
    entityIds: Array<string>;
    /**
     * Reference to perception sample
     * @type {string}
     * @memberof RunSimulationRequestContext
     */
    mediaSampleId?: string;
    /**
     * Optional Talos-specific context
     * @type {{ [key: string]: any; }}
     * @memberof RunSimulationRequestContext
     */
    talosMetadata?: { [key: string]: any; };
    /**
     * Number of steps to simulate ahead
     * @type {number}
     * @memberof RunSimulationRequestContext
     */
    horizonSteps?: number;
}

/**
 * Check if a given object implements the RunSimulationRequestContext interface.
 */
export function instanceOfRunSimulationRequestContext(value: object): value is RunSimulationRequestContext {
    if (!('entityIds' in value) || value['entityIds'] === undefined) return false;
    return true;
}

export function RunSimulationRequestContextFromJSON(json: any): RunSimulationRequestContext {
    return RunSimulationRequestContextFromJSONTyped(json, false);
}

export function RunSimulationRequestContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunSimulationRequestContext {
    if (json == null) {
        return json;
    }
    return {
        
        'entityIds': json['entity_ids'],
        'mediaSampleId': json['media_sample_id'] == null ? undefined : json['media_sample_id'],
        'talosMetadata': json['talos_metadata'] == null ? undefined : json['talos_metadata'],
        'horizonSteps': json['horizon_steps'] == null ? undefined : json['horizon_steps'],
    };
}

export function RunSimulationRequestContextToJSON(json: any): RunSimulationRequestContext {
    return RunSimulationRequestContextToJSONTyped(json, false);
}

export function RunSimulationRequestContextToJSONTyped(value?: RunSimulationRequestContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity_ids': value['entityIds'],
        'media_sample_id': value['mediaSampleId'],
        'talos_metadata': value['talosMetadata'],
        'horizon_steps': value['horizonSteps'],
    };
}

