/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunSimulation200ResponseMetadata
 */
export interface RunSimulation200ResponseMetadata {
    /**
     * 
     * @type {string}
     * @memberof RunSimulation200ResponseMetadata
     */
    modelVersion?: string;
    /**
     * 
     * @type {number}
     * @memberof RunSimulation200ResponseMetadata
     */
    horizon?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof RunSimulation200ResponseMetadata
     */
    assumptions?: Array<string>;
}

/**
 * Check if a given object implements the RunSimulation200ResponseMetadata interface.
 */
export function instanceOfRunSimulation200ResponseMetadata(value: object): value is RunSimulation200ResponseMetadata {
    return true;
}

export function RunSimulation200ResponseMetadataFromJSON(json: any): RunSimulation200ResponseMetadata {
    return RunSimulation200ResponseMetadataFromJSONTyped(json, false);
}

export function RunSimulation200ResponseMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunSimulation200ResponseMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'modelVersion': json['model_version'] == null ? undefined : json['model_version'],
        'horizon': json['horizon'] == null ? undefined : json['horizon'],
        'assumptions': json['assumptions'] == null ? undefined : json['assumptions'],
    };
}

export function RunSimulation200ResponseMetadataToJSON(json: any): RunSimulation200ResponseMetadata {
    return RunSimulation200ResponseMetadataToJSONTyped(json, false);
}

export function RunSimulation200ResponseMetadataToJSONTyped(value?: RunSimulation200ResponseMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model_version': value['modelVersion'],
        'horizon': value['horizon'],
        'assumptions': value['assumptions'],
    };
}

