/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunSimulation200ResponsePredictedOutcomesInner
 */
export interface RunSimulation200ResponsePredictedOutcomesInner {
    /**
     * 
     * @type {string}
     * @memberof RunSimulation200ResponsePredictedOutcomesInner
     */
    entityId?: string;
    /**
     * 
     * @type {string}
     * @memberof RunSimulation200ResponsePredictedOutcomesInner
     */
    predictedState?: string;
    /**
     * 
     * @type {number}
     * @memberof RunSimulation200ResponsePredictedOutcomesInner
     */
    confidence?: number;
    /**
     * 
     * @type {number}
     * @memberof RunSimulation200ResponsePredictedOutcomesInner
     */
    timestep?: number;
}

/**
 * Check if a given object implements the RunSimulation200ResponsePredictedOutcomesInner interface.
 */
export function instanceOfRunSimulation200ResponsePredictedOutcomesInner(value: object): value is RunSimulation200ResponsePredictedOutcomesInner {
    return true;
}

export function RunSimulation200ResponsePredictedOutcomesInnerFromJSON(json: any): RunSimulation200ResponsePredictedOutcomesInner {
    return RunSimulation200ResponsePredictedOutcomesInnerFromJSONTyped(json, false);
}

export function RunSimulation200ResponsePredictedOutcomesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunSimulation200ResponsePredictedOutcomesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'entityId': json['entity_id'] == null ? undefined : json['entity_id'],
        'predictedState': json['predicted_state'] == null ? undefined : json['predicted_state'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'timestep': json['timestep'] == null ? undefined : json['timestep'],
    };
}

export function RunSimulation200ResponsePredictedOutcomesInnerToJSON(json: any): RunSimulation200ResponsePredictedOutcomesInner {
    return RunSimulation200ResponsePredictedOutcomesInnerToJSONTyped(json, false);
}

export function RunSimulation200ResponsePredictedOutcomesInnerToJSONTyped(value?: RunSimulation200ResponsePredictedOutcomesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity_id': value['entityId'],
        'predicted_state': value['predictedState'],
        'confidence': value['confidence'],
        'timestep': value['timestep'],
    };
}

