/* tslint:disable */
/* eslint-disable */
/**
 * Sophia API
 * Canonical Sophia OpenAPI contract for Project LOGOS. See Project LOGOS spec: Phase 2 Section - Sophia service deliverables.  Sophia is the non-linguistic cognitive core providing: - Plan generation and execution - State management and queries - Simulation and imagination capabilities  All endpoints interact with the HCG (Neo4j + Milvus) and maintain causal coherence. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CWMState } from './CWMState';
import {
    CWMStateFromJSON,
    CWMStateFromJSONTyped,
    CWMStateToJSON,
    CWMStateToJSONTyped,
} from './CWMState';
import type { RunSimulation200ResponsePredictedOutcomesInner } from './RunSimulation200ResponsePredictedOutcomesInner';
import {
    RunSimulation200ResponsePredictedOutcomesInnerFromJSON,
    RunSimulation200ResponsePredictedOutcomesInnerFromJSONTyped,
    RunSimulation200ResponsePredictedOutcomesInnerToJSON,
    RunSimulation200ResponsePredictedOutcomesInnerToJSONTyped,
} from './RunSimulation200ResponsePredictedOutcomesInner';
import type { RunSimulation200ResponseMetadata } from './RunSimulation200ResponseMetadata';
import {
    RunSimulation200ResponseMetadataFromJSON,
    RunSimulation200ResponseMetadataFromJSONTyped,
    RunSimulation200ResponseMetadataToJSON,
    RunSimulation200ResponseMetadataToJSONTyped,
} from './RunSimulation200ResponseMetadata';

/**
 * 
 * @export
 * @interface RunSimulation200Response
 */
export interface RunSimulation200Response {
    /**
     * Unique identifier for this simulation run
     * @type {string}
     * @memberof RunSimulation200Response
     */
    simulationId?: string;
    /**
     * 
     * @type {Array<CWMState>}
     * @memberof RunSimulation200Response
     */
    imaginedStates?: Array<CWMState>;
    /**
     * 
     * @type {Array<RunSimulation200ResponsePredictedOutcomesInner>}
     * @memberof RunSimulation200Response
     */
    predictedOutcomes?: Array<RunSimulation200ResponsePredictedOutcomesInner>;
    /**
     * 
     * @type {RunSimulation200ResponseMetadata}
     * @memberof RunSimulation200Response
     */
    metadata?: RunSimulation200ResponseMetadata;
}

/**
 * Check if a given object implements the RunSimulation200Response interface.
 */
export function instanceOfRunSimulation200Response(value: object): value is RunSimulation200Response {
    return true;
}

export function RunSimulation200ResponseFromJSON(json: any): RunSimulation200Response {
    return RunSimulation200ResponseFromJSONTyped(json, false);
}

export function RunSimulation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunSimulation200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'simulationId': json['simulation_id'] == null ? undefined : json['simulation_id'],
        'imaginedStates': json['imagined_states'] == null ? undefined : ((json['imagined_states'] as Array<any>).map(CWMStateFromJSON)),
        'predictedOutcomes': json['predicted_outcomes'] == null ? undefined : ((json['predicted_outcomes'] as Array<any>).map(RunSimulation200ResponsePredictedOutcomesInnerFromJSON)),
        'metadata': json['metadata'] == null ? undefined : RunSimulation200ResponseMetadataFromJSON(json['metadata']),
    };
}

export function RunSimulation200ResponseToJSON(json: any): RunSimulation200Response {
    return RunSimulation200ResponseToJSONTyped(json, false);
}

export function RunSimulation200ResponseToJSONTyped(value?: RunSimulation200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simulation_id': value['simulationId'],
        'imagined_states': value['imaginedStates'] == null ? undefined : ((value['imaginedStates'] as Array<any>).map(CWMStateToJSON)),
        'predicted_outcomes': value['predictedOutcomes'] == null ? undefined : ((value['predictedOutcomes'] as Array<any>).map(RunSimulation200ResponsePredictedOutcomesInnerToJSON)),
        'metadata': RunSimulation200ResponseMetadataToJSON(value['metadata']),
    };
}

