/* tslint:disable */
/* eslint-disable */
/**
 * Hermes API
 * Stateless language & embedding tools for Project LOGOS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmbedTextRequest,
  EmbedTextResponse,
  HTTPValidationError,
  HealthResponse,
  LLMRequest,
  LLMResponse,
  STTResponse,
  SimpleNLPRequest,
  SimpleNLPResponse,
  TTSRequest,
} from '../models/index';
import {
    EmbedTextRequestFromJSON,
    EmbedTextRequestToJSON,
    EmbedTextResponseFromJSON,
    EmbedTextResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    HealthResponseFromJSON,
    HealthResponseToJSON,
    LLMRequestFromJSON,
    LLMRequestToJSON,
    LLMResponseFromJSON,
    LLMResponseToJSON,
    STTResponseFromJSON,
    STTResponseToJSON,
    SimpleNLPRequestFromJSON,
    SimpleNLPRequestToJSON,
    SimpleNLPResponseFromJSON,
    SimpleNLPResponseToJSON,
    TTSRequestFromJSON,
    TTSRequestToJSON,
} from '../models/index';

export interface EmbedTextEmbedTextPostRequest {
    embedTextRequest: EmbedTextRequest;
}

export interface LlmGenerateLlmPostRequest {
    lLMRequest: LLMRequest;
}

export interface SimpleNlpSimpleNlpPostRequest {
    simpleNLPRequest: SimpleNLPRequest;
}

export interface SpeechToTextSttPostRequest {
    audio: Blob;
    language?: string;
}

export interface TextToSpeechTtsPostRequest {
    tTSRequest: TTSRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Generate vector embeddings for input text.  Args:     request: EmbedTextRequest with text and model  Returns:     EmbedTextResponse with embedding vector
     * Embed Text
     */
    async embedTextEmbedTextPostRaw(requestParameters: EmbedTextEmbedTextPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmbedTextResponse>> {
        if (requestParameters['embedTextRequest'] == null) {
            throw new runtime.RequiredError(
                'embedTextRequest',
                'Required parameter "embedTextRequest" was null or undefined when calling embedTextEmbedTextPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/embed_text`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmbedTextRequestToJSON(requestParameters['embedTextRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmbedTextResponseFromJSON(jsonValue));
    }

    /**
     * Generate vector embeddings for input text.  Args:     request: EmbedTextRequest with text and model  Returns:     EmbedTextResponse with embedding vector
     * Embed Text
     */
    async embedTextEmbedTextPost(requestParameters: EmbedTextEmbedTextPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmbedTextResponse> {
        const response = await this.embedTextEmbedTextPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Health check endpoint with detailed service status.  Returns the overall health status and availability of ML services, Milvus connectivity, and internal queue status. This is useful for monitoring and integration with other LOGOS components.
     * Health
     */
    async healthHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
    }

    /**
     * Health check endpoint with detailed service status.  Returns the overall health status and availability of ML services, Milvus connectivity, and internal queue status. This is useful for monitoring and integration with other LOGOS components.
     * Health
     */
    async healthHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse> {
        const response = await this.healthHealthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Proxy language model completions through Hermes.
     * Llm Generate
     */
    async llmGenerateLlmPostRaw(requestParameters: LlmGenerateLlmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LLMResponse>> {
        if (requestParameters['lLMRequest'] == null) {
            throw new runtime.RequiredError(
                'lLMRequest',
                'Required parameter "lLMRequest" was null or undefined when calling llmGenerateLlmPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/llm`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LLMRequestToJSON(requestParameters['lLMRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LLMResponseFromJSON(jsonValue));
    }

    /**
     * Proxy language model completions through Hermes.
     * Llm Generate
     */
    async llmGenerateLlmPost(requestParameters: LlmGenerateLlmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LLMResponse> {
        const response = await this.llmGenerateLlmPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Root endpoint with API information.
     * Root
     */
    async rootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Root endpoint with API information.
     * Root
     */
    async rootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.rootGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Perform basic NLP preprocessing.  Args:     request: SimpleNLPRequest with text and operations  Returns:     SimpleNLPResponse with requested NLP results
     * Simple Nlp
     */
    async simpleNlpSimpleNlpPostRaw(requestParameters: SimpleNlpSimpleNlpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleNLPResponse>> {
        if (requestParameters['simpleNLPRequest'] == null) {
            throw new runtime.RequiredError(
                'simpleNLPRequest',
                'Required parameter "simpleNLPRequest" was null or undefined when calling simpleNlpSimpleNlpPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/simple_nlp`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SimpleNLPRequestToJSON(requestParameters['simpleNLPRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleNLPResponseFromJSON(jsonValue));
    }

    /**
     * Perform basic NLP preprocessing.  Args:     request: SimpleNLPRequest with text and operations  Returns:     SimpleNLPResponse with requested NLP results
     * Simple Nlp
     */
    async simpleNlpSimpleNlpPost(requestParameters: SimpleNlpSimpleNlpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleNLPResponse> {
        const response = await this.simpleNlpSimpleNlpPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Convert audio input to text transcription.  Args:     audio: Audio file to transcribe     language: Optional language hint (e.g., \"en-US\")  Returns:     STTResponse with transcribed text and confidence score
     * Speech To Text
     */
    async speechToTextSttPostRaw(requestParameters: SpeechToTextSttPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<STTResponse>> {
        if (requestParameters['audio'] == null) {
            throw new runtime.RequiredError(
                'audio',
                'Required parameter "audio" was null or undefined when calling speechToTextSttPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['audio'] != null) {
            formParams.append('audio', requestParameters['audio'] as any);
        }


        let urlPath = `/stt`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => STTResponseFromJSON(jsonValue));
    }

    /**
     * Convert audio input to text transcription.  Args:     audio: Audio file to transcribe     language: Optional language hint (e.g., \"en-US\")  Returns:     STTResponse with transcribed text and confidence score
     * Speech To Text
     */
    async speechToTextSttPost(requestParameters: SpeechToTextSttPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<STTResponse> {
        const response = await this.speechToTextSttPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Convert text to synthesized speech audio.  Args:     request: TTSRequest with text, voice, and language  Returns:     Audio file in WAV format
     * Text To Speech
     */
    async textToSpeechTtsPostRaw(requestParameters: TextToSpeechTtsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['tTSRequest'] == null) {
            throw new runtime.RequiredError(
                'tTSRequest',
                'Required parameter "tTSRequest" was null or undefined when calling textToSpeechTtsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/tts`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TTSRequestToJSON(requestParameters['tTSRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Convert text to synthesized speech audio.  Args:     request: TTSRequest with text, voice, and language  Returns:     Audio file in WAV format
     * Text To Speech
     */
    async textToSpeechTtsPost(requestParameters: TextToSpeechTtsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.textToSpeechTtsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
